import { useTranslation } from 'react-i18next';
import type { AgentSelectabilityReasonLabels } from '@/lib/agentSelectability';

export function useShellCopy() {
  const { t } = useTranslation();

  return {
    brandName: t('shell.brandName'),
    brandSystemName: t('shell.brandSystemName'),
    brandSignature: t('shell.brandSignature'),
    workspaceLabel: t('shell.workspaceLabel'),
    systemClockLabel: t('shell.systemClockLabel'),
    commandLabel: t('shell.commandLabel'),
    statusLabel: t('shell.statusLabel'),
    statusValue: t('shell.statusValue'),
    manifesto: t('shell.manifesto', { returnObjects: true }) as string[],
    footerProjectLabel: t('shell.footerProjectLabel'),
    footerProjectValue: t('shell.footerProjectValue'),
    footerRevisionLabel: t('shell.footerRevisionLabel'),
    footerRevisionValue: t('shell.footerRevisionValue'),
    footerStatusLabel: t('shell.footerStatusLabel'),
    footerStatusValue: t('shell.footerStatusValue'),
    footerTagline: t('shell.footerTagline'),
    footerVersion: t('shell.footerVersion'),
    railStatement: t('shell.railStatement'),
    railSummary: t('shell.railSummary'),
    navItems: [
      { to: '/', key: 'overview', label: t('shell.nav.overview.label'), hint: t('shell.nav.overview.hint') },
      { to: '/board', key: 'board', label: t('shell.nav.board.label'), hint: t('shell.nav.board.hint') },
      { to: '/projects', key: 'projects', label: t('shell.nav.projects.label'), hint: t('shell.nav.projects.hint') },
      { to: '/tasks', key: 'tasks', label: t('shell.nav.tasks.label'), hint: t('shell.nav.tasks.hint') },
      { to: '/agents', key: 'agents', label: t('shell.nav.agents.label'), hint: t('shell.nav.agents.hint') },
      { to: '/todos', key: 'todos', label: t('shell.nav.todos.label'), hint: t('shell.nav.todos.hint') },
      { to: '/archive', key: 'archive', label: t('shell.nav.archive.label'), hint: t('shell.nav.archive.hint') },
      { to: '/templates', key: 'templates', label: t('shell.nav.templates.label'), hint: t('shell.nav.templates.hint') },
      { to: '/tasks/new', key: 'create', label: t('shell.nav.create.label'), hint: t('shell.nav.create.hint') },
      { to: '/reviews', key: 'reviews', label: t('shell.nav.reviews.label'), hint: t('shell.nav.reviews.hint') },
      { to: '/settings', key: 'settings', label: t('shell.nav.settings.label'), hint: t('shell.nav.settings.hint') },
    ],
  };
}

export function usePageMetaCopy() {
  const { t } = useTranslation();

  return {
    '/': { title: t('pageMeta.home.title') },
    '/board': { title: t('pageMeta.board.title') },
    '/projects': { title: t('pageMeta.projects.title') },
    '/tasks': { title: t('pageMeta.tasks.title') },
    '/agents': { title: t('pageMeta.agents.title') },
    '/todos': { title: t('pageMeta.todos.title') },
    '/archive': { title: t('pageMeta.archive.title') },
    '/templates': { title: t('pageMeta.templates.title') },
    '/tasks/new': { title: t('pageMeta.createTask.title') },
    '/reviews': { title: t('pageMeta.reviews.title') },
    '/settings': { title: t('pageMeta.settings.title') },
  } as const;
}

export function useDashboardHomeCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('home.kicker'),
    title: t('home.title'),
    summary: t('home.summary'),
    slogan: t('home.slogan'),
    sectionLabels: {
      agora: t('home.sectionLabels.agora'),
      archon: t('home.sectionLabels.archon'),
      pipeline: t('home.sectionLabels.pipeline'),
    },
    commandAuthorityLabel: t('home.commandAuthorityLabel'),
    pendingResolutionLabel: t('home.pendingResolutionLabel'),
    executionLabel: t('home.executionLabel'),
    topologyLabel: t('home.topologyLabel'),
    terminalLabel: t('home.terminalLabel'),
    systemLoadLabel: t('home.systemLoadLabel'),
    architectureLabel: t('home.architectureLabel'),
    primaryAction: t('home.primaryAction'),
    secondaryAction: t('home.secondaryAction'),
    tertiaryAction: t('home.tertiaryAction'),
    syncErrorMessage: t('home.syncErrorMessage'),
    pulseKicker: t('home.pulseKicker'),
    pulseTitle: t('home.pulseTitle'),
    pulseStatusLoading: t('home.pulseStatusLoading'),
    pulseStatusReady: t('home.pulseStatusReady'),
    pulseOrbitLabels: {
      left: t('home.pulseOrbitLabels.left'),
      right: t('home.pulseOrbitLabels.right'),
      bottom: t('home.pulseOrbitLabels.bottom'),
    },
    pulseItemLabels: {
      running: t('home.pulseItems.running.label'),
      waiting: t('home.pulseItems.waiting.label'),
      latestCompleted: t('home.pulseItems.latestCompleted.label'),
    },
    sideNotes: [
      {
        kicker: t('home.sideNotes.brand.kicker'),
        title: t('home.sideNotes.brand.title'),
        body: t('home.sideNotes.brand.body'),
      },
      {
        kicker: t('home.sideNotes.promise.kicker'),
        title: t('home.sideNotes.promise.title'),
        body: t('home.sideNotes.promise.body'),
      },
    ],
    metricLabels: {
      active: t('home.metrics.activeLabel'),
      waiting: t('home.metrics.waitingLabel'),
      participants: t('home.metrics.participantsLabel'),
      latestCompleted: t('home.metrics.latestCompletedLabel'),
      activeExecutions: t('home.metrics.activeExecutionsLabel'),
      hostLoad: t('home.metrics.hostLoadLabel'),
    },
    metricNotes: {
      active: t('home.metrics.activeNote'),
      waiting: t('home.metrics.waitingNote'),
      participants: t('home.metrics.participantsNote'),
      latestCompleted: t('home.metrics.latestCompletedNote'),
      activeExecutions: t('home.metrics.activeExecutionsNote'),
      hostLoad: t('home.metrics.hostLoadNote'),
    },
    latestCompletedFallback: t('home.latestCompletedFallback'),
    feedKicker: t('home.feedKicker'),
    feedTitle: t('home.feedTitle'),
    feedAction: t('home.feedAction'),
    feedEmpty: t('home.feedEmpty'),
    emptyTaskDescription: t('home.emptyTaskDescription'),
    fallbackDecisionStage: t('home.fallbackDecisionStage'),
    reviewKicker: t('home.reviewKicker'),
    reviewTitle: t('home.reviewTitle'),
    reviewCountUnit: t('home.reviewCountUnit'),
    reviewDescriptionPrefix: t('home.reviewDescriptionPrefix'),
    reviewDeck: {
      previous: t('home.reviewDeck.previous'),
      next: t('home.reviewDeck.next'),
      position: t('home.reviewDeck.position'),
    },
    principleKicker: t('home.principleKicker'),
    principleTitle: t('home.principleTitle'),
    principleBullets: t('home.principleBullets', { returnObjects: true }) as string[],
    resolutionTitle: t('home.resolutionTitle'),
    resolutionSummary: t('home.resolutionSummary'),
    resolutionEmptyTitle: t('home.resolutionEmptyTitle'),
    resolutionEmptySummary: t('home.resolutionEmptySummary'),
    resolutionEmptyValue: t('home.resolutionEmptyValue'),
    resolutionMeta: {
      gate: t('home.resolutionMeta.gate'),
      stage: t('home.resolutionMeta.stage'),
    },
    resolutionFallbacks: {
      gate: t('home.resolutionFallbacks.gate'),
      stage: t('home.resolutionFallbacks.stage'),
      summary: t('home.resolutionFallbacks.summary'),
    },
    resolutionActions: {
      authorize: t('home.resolutionActions.authorize'),
      veto: t('home.resolutionActions.veto'),
      synthesize: t('home.resolutionActions.synthesize'),
    },
    terminalStatusPrefix: t('home.terminalStatusPrefix'),
    terminalEmpty: t('home.terminalEmpty'),
    topologyHashLabel: t('home.topologyHashLabel'),
    topologyHashValue: t('home.topologyHashValue'),
    topologyNodes: t('home.topologyNodes', { returnObjects: true }) as string[],
    loadEstimateNote: t('home.loadEstimateNote'),
    governance: {
      kicker: t('home.governance.kicker'),
      title: t('home.governance.title'),
      hostMemory: t('home.governance.hostMemory'),
      pressureStatus: t('home.governance.pressureStatus'),
      runtimeStatus: t('home.governance.runtimeStatus'),
      escalationStatus: t('home.governance.escalationStatus'),
      warningsTitle: t('home.governance.warningsTitle'),
      executionDetailsTitle: t('home.governance.executionDetailsTitle'),
      assigneeTitle: t('home.governance.assigneeTitle'),
      emptyAssignee: t('home.governance.emptyAssignee'),
      emptyWarnings: t('home.governance.emptyWarnings'),
      emptyExecutionDetails: t('home.governance.emptyExecutionDetails'),
    },
    taskRailLabels: {
      selectedTask: t('home.taskRailLabels.selectedTask'),
      executionLoop: t('home.taskRailLabels.executionLoop'),
      runtimeLog: t('home.taskRailLabels.runtimeLog'),
      stageFallback: t('home.taskRailLabels.stageFallback'),
      logEmpty: t('home.taskRailLabels.logEmpty'),
      focusPrompt: t('home.taskRailLabels.focusPrompt'),
      taskEmpty: t('home.taskRailLabels.taskEmpty'),
    },
    proposalToneLabels: {
      constraint: t('home.proposalToneLabels.constraint'),
      optimize: t('home.proposalToneLabels.optimize'),
      observe: t('home.proposalToneLabels.observe'),
    },
    loadReadoutLabel: t('home.loadReadoutLabel'),
    constraintSignals: {
      waiting: t('home.constraintSignals.waiting'),
      stable: t('home.constraintSignals.stable'),
    },
  };
}

export function useBoardPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('board.kicker'),
    title: t('board.title'),
    summary: t('board.summary'),
    createAction: t('board.createAction'),
    emptyTitle: t('board.emptyTitle'),
    emptySummary: t('board.emptySummary'),
    columns: {
      pending: t('board.columns.pending'),
      inProgress: t('board.columns.inProgress'),
      gateWaiting: t('board.columns.gateWaiting'),
      completed: t('board.columns.completed'),
      interrupted: t('board.columns.interrupted'),
    },
  };
}

export function useCreateTaskPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('createTask.kicker'),
    title: t('createTask.title'),
    summary: t('createTask.summary'),
    titleLabel: t('createTask.titleLabel'),
    titlePlaceholder: t('createTask.titlePlaceholder'),
    projectLabel: t('createTask.projectLabel'),
    noProjectOption: t('createTask.noProjectOption'),
    descriptionLabel: t('createTask.descriptionLabel'),
    descriptionPlaceholder: t('createTask.descriptionPlaceholder'),
    typeLabel: t('createTask.typeLabel'),
    priorityLabel: t('createTask.priorityLabel'),
    globalSkillsLabel: t('createTask.globalSkillsLabel'),
    roleSkillsLabel: t('createTask.roleSkillsLabel'),
    noSkillsLabel: t('createTask.noSkillsLabel'),
    noSkillResultsLabel: t('createTask.noSkillResultsLabel'),
    noRoleSkillsSelectedLabel: t('createTask.noRoleSkillsSelectedLabel'),
    selectedSkillsCount: (count: number) => t('createTask.selectedSkillsCount', { count }),
    selectedSkillToggleHint: t('createTask.selectedSkillToggleHint'),
    deselectSkillTitle: (skillRef: string) => t('createTask.deselectSkillTitle', { skillRef }),
    openGlobalSkillsAction: t('createTask.openGlobalSkillsAction'),
    closeGlobalSkillsAction: t('createTask.closeGlobalSkillsAction'),
    globalSkillsSearchLabel: t('createTask.globalSkillsSearchLabel'),
    globalSkillsSearchPlaceholder: t('createTask.globalSkillsSearchPlaceholder'),
    skillSignalLabels: {
      recommended: t('createTask.skillSignalLabels.recommended'),
      recent: t('createTask.skillSignalLabels.recent'),
    },
    openRoleSkillsAction: (role: string) => t('createTask.openRoleSkillsAction', { role }),
    closeRoleSkillsAction: (role: string) => t('createTask.closeRoleSkillsAction', { role }),
    roleSkillsSearchLabel: (role: string) => t('createTask.roleSkillsSearchLabel', { role }),
    roleSkillsSearchPlaceholder: t('createTask.roleSkillsSearchPlaceholder'),
    templateLabel: t('createTask.templateLabel'),
    teamLabel: t('createTask.teamLabel'),
    controllerLabel: t('createTask.controllerLabel'),
    threadLabel: t('createTask.threadLabel'),
    privateThreadLabel: t('createTask.privateThreadLabel'),
    teamSummary: t('createTask.teamSummary'),
    noAgentLabel: t('createTask.noAgentLabel'),
    restrictedSuggestedLabel: t('createTask.restrictedSuggestedLabel'),
    selectabilityReasonLabel: t('createTask.selectabilityReasonLabel'),
    selectabilityReasonLabels: {
      active_assignment: t('selectabilityReasons.active_assignment'),
      inventory_launchable: t('selectabilityReasons.inventory_launchable'),
      stale_observation: t('selectabilityReasons.stale_observation'),
      provider_disconnected: t('selectabilityReasons.provider_disconnected'),
      unbound_agent: t('selectabilityReasons.unbound_agent'),
      legacy_presence_gate: t('selectabilityReasons.legacy_presence_gate'),
      legacy_presence_ok: t('selectabilityReasons.legacy_presence_ok'),
      unknown: t('selectabilityReasons.unknown'),
    } satisfies AgentSelectabilityReasonLabels,
    sourceContextTitle: t('createTask.sourceContextTitle'),
    sourceContextSummary: t('createTask.sourceContextSummary'),
    sourceKindLabel: t('createTask.sourceKindLabel'),
    sourceTitleFieldLabel: t('createTask.sourceTitleFieldLabel'),
    sourceRefLabel: t('createTask.sourceRefLabel'),
    sourceTaskIdsLabel: t('createTask.sourceTaskIdsLabel'),
    sourceSnippetLabel: t('createTask.sourceSnippetLabel'),
    sourceKindLabels: {
      knowledge: t('createTask.sourceKindLabels.knowledge'),
      recap: t('createTask.sourceKindLabels.recap'),
      citizen: t('createTask.sourceKindLabels.citizen'),
    },
    submitAction: t('createTask.submitAction'),
    submittingAction: t('createTask.submittingAction'),
    backAction: t('createTask.backAction'),
    taskTypes: [
      { value: 'coding', label: t('createTask.taskType.coding') },
      { value: 'quick', label: t('createTask.taskType.quick') },
      { value: 'document', label: t('createTask.taskType.document') },
      { value: 'research', label: t('createTask.taskType.research') },
    ] as const,
  };
}

export function useProjectsPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('projectsPage.kicker'),
    title: t('projectsPage.title'),
    summary: t('projectsPage.summary'),
    countLabel: t('projectsPage.countLabel'),
    createToggleAction: t('projectsPage.createToggleAction'),
    nameLabel: t('projectsPage.nameLabel'),
    namePlaceholder: t('projectsPage.namePlaceholder'),
    summaryLabel: t('projectsPage.summaryLabel'),
    summaryPlaceholder: t('projectsPage.summaryPlaceholder'),
    confirmAction: t('projectsPage.confirmAction'),
    creatingAction: t('projectsPage.creatingAction'),
    loadingTitle: t('projectsPage.loadingTitle'),
    emptyTitle: t('projectsPage.emptyTitle'),
  };
}

export function useProjectDetailPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('projectDetail.kicker'),
    loadingTitle: t('projectDetail.loadingTitle'),
    notFoundTitle: t('projectDetail.notFoundTitle'),
    emptySummary: t('projectDetail.emptySummary'),
    openBrainAction: t('projectDetail.openBrainAction'),
    stats: {
      knowledge: t('projectDetail.stats.knowledge'),
      citizens: t('projectDetail.stats.citizens'),
      recaps: t('projectDetail.stats.recaps'),
      activeTasks: t('projectDetail.stats.activeTasks'),
      waitingReview: t('projectDetail.stats.waitingReview'),
      pendingTodos: t('projectDetail.stats.pendingTodos'),
    },
    recapsTitle: t('projectDetail.recapsTitle'),
    recapsEmpty: t('projectDetail.recapsEmpty'),
    openRecapAria: (title: string) => t('projectDetail.openRecapAria', { title }),
    knowledgeTitle: t('projectDetail.knowledgeTitle'),
    knowledgeEmpty: t('projectDetail.knowledgeEmpty'),
    openKnowledgeAria: (title: string) => t('projectDetail.openKnowledgeAria', { title }),
    relatedTasksTitle: t('projectDetail.relatedTasksTitle'),
    taskFilters: {
      all: t('projectDetail.taskFilters.all'),
      active: t('projectDetail.taskFilters.active'),
      review: t('projectDetail.taskFilters.review'),
    },
    relatedTasksEmpty: t('projectDetail.relatedTasksEmpty'),
    citizensTitle: t('projectDetail.citizensTitle'),
    createTaskAction: t('projectDetail.createTaskAction'),
    createTodoAction: t('projectDetail.createTodoAction'),
    citizensEmpty: t('projectDetail.citizensEmpty'),
    citizenPreviewLabel: t('projectDetail.citizenPreviewLabel'),
    openCitizenAria: (name: string) => t('projectDetail.openCitizenAria', { name }),
    relatedTodosTitle: t('projectDetail.relatedTodosTitle'),
    todoFilters: {
      all: t('projectDetail.todoFilters.all'),
      pending: t('projectDetail.todoFilters.pending'),
    },
    relatedTodosEmpty: t('projectDetail.relatedTodosEmpty'),
    reopenTodoAction: t('projectDetail.reopenTodoAction'),
    markTodoDoneAction: t('projectDetail.markTodoDoneAction'),
    promoteTodoAction: t('projectDetail.promoteTodoAction'),
    deleteTodoAction: t('projectDetail.deleteTodoAction'),
    recapDialogLabel: t('projectDetail.recapDialogLabel'),
    recapContentTitle: t('projectDetail.recapContentTitle'),
    documentFallback: t('projectDetail.documentFallback'),
    knowledgeDialogLabel: t('projectDetail.knowledgeDialogLabel'),
    knowledgeSourceTasksTitle: t('projectDetail.knowledgeSourceTasksTitle'),
    noSourceTasks: t('projectDetail.noSourceTasks'),
    knowledgeContentTitle: t('projectDetail.knowledgeContentTitle'),
    citizenDialogLabel: t('projectDetail.citizenDialogLabel'),
    personaTitle: t('projectDetail.personaTitle'),
    noPersona: t('projectDetail.noPersona'),
    boundariesTitle: t('projectDetail.boundariesTitle'),
    noBoundaries: t('projectDetail.noBoundaries'),
    skillsTitle: t('projectDetail.skillsTitle'),
    noSkills: t('projectDetail.noSkills'),
    channelPoliciesTitle: t('projectDetail.channelPoliciesTitle'),
    runtimeMetadataTitle: t('projectDetail.runtimeMetadataTitle'),
  };
}

export function useProjectBrainPageCopy() {
  const { t } = useTranslation();

  return {
    loadingTitle: t('projectBrain.loadingTitle'),
    notFoundTitle: t('projectBrain.notFoundTitle'),
    kicker: t('projectBrain.kicker'),
    title: t('projectBrain.title'),
    surfaceTitle: t('projectBrain.surfaceTitle'),
    filters: {
      all: t('projectBrain.filters.all'),
      core: t('projectBrain.filters.core'),
      knowledge: t('projectBrain.filters.knowledge'),
      recaps: t('projectBrain.filters.recaps'),
      citizens: t('projectBrain.filters.citizens'),
    },
    searchLabel: t('projectBrain.searchLabel'),
    searchPlaceholder: t('projectBrain.searchPlaceholder'),
    openBrainItemAria: (label: string) => t('projectBrain.openBrainItemAria', { label }),
    emptyListTitle: t('projectBrain.emptyListTitle'),
    detailEmptyTitle: t('projectBrain.detailEmptyTitle'),
    detailEmptySummary: t('projectBrain.detailEmptySummary'),
    indexFallbackTitle: t('projectBrain.indexFallbackTitle'),
    timelineFallbackTitle: t('projectBrain.timelineFallbackTitle'),
    sourceTasksTitle: t('projectBrain.sourceTasksTitle'),
    noSourceTasks: t('projectBrain.noSourceTasks'),
    openSourceTaskAction: (taskId: string) => t('projectBrain.openSourceTaskAction', { taskId }),
    citizenIdentityTitle: t('projectBrain.citizenIdentityTitle'),
    personaTitle: t('projectBrain.personaTitle'),
    noPersona: t('projectBrain.noPersona'),
    boundariesTitle: t('projectBrain.boundariesTitle'),
    noBoundaries: t('projectBrain.noBoundaries'),
    skillsTitle: t('projectBrain.skillsTitle'),
    noSkills: t('projectBrain.noSkills'),
    channelPoliciesTitle: t('projectBrain.channelPoliciesTitle'),
    runtimeMetadataTitle: t('projectBrain.runtimeMetadataTitle'),
    contentTitle: t('projectBrain.contentTitle'),
    actionBridgeTitle: t('projectBrain.actionBridgeTitle'),
    backToProjectDetailAction: t('projectBrain.backToProjectDetailAction'),
    createTaskInProjectAction: t('projectBrain.createTaskInProjectAction'),
    createTodoInProjectAction: t('projectBrain.createTodoInProjectAction'),
    kindLabels: {
      core: t('projectBrain.kindLabels.core'),
      recap: t('projectBrain.kindLabels.recap'),
      knowledge: t('projectBrain.kindLabels.knowledge'),
      citizen: t('projectBrain.kindLabels.citizen'),
    },
  };
}

export function useTasksPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('tasks.kicker'),
    title: t('tasks.title'),
    summary: t('tasks.summary'),
    workbenchTitle: t('tasks.workbenchTitle'),
    workbenchSummary: t('tasks.workbenchSummary'),
    filterAction: t('tasks.filterAction'),
    clearFiltersAction: t('tasks.clearFiltersAction'),
    applyFiltersAction: t('tasks.applyFiltersAction'),
    detailAction: t('tasks.detailAction'),
    detailDialogLabel: t('tasks.detailDialogLabel'),
    detailDialogTitle: t('tasks.detailDialogTitle'),
    detailLoadingTitle: t('tasks.detailLoadingTitle'),
    detailLoadingSummary: t('tasks.detailLoadingSummary'),
    detailErrorTitle: t('tasks.detailErrorTitle'),
    detailEmptyTitle: t('tasks.detailEmptyTitle'),
    detailEmptySummary: t('tasks.detailEmptySummary'),
    quickViewTitle: t('tasks.quickViewTitle'),
    filterSectionLabels: {
      state: t('tasks.filterSectionLabels.state'),
      priority: t('tasks.filterSectionLabels.priority'),
      team: t('tasks.filterSectionLabels.team'),
      workflow: t('tasks.filterSectionLabels.workflow'),
    },
    filterEmpty: t('tasks.filterEmpty'),
    activeFilterPrefix: t('tasks.activeFilterPrefix'),
    searchPlaceholder: t('tasks.searchPlaceholder'),
    listKicker: t('tasks.listKicker'),
    listTitle: t('tasks.listTitle'),
    listCountUnit: t('tasks.listCountUnit'),
    detailKicker: t('tasks.detailKicker'),
    stageLabel: t('tasks.stageLabel'),
    stageFallback: t('tasks.stageFallback'),
    workflowLabel: t('tasks.workflowLabel'),
    teamLabel: t('tasks.teamLabel'),
    controllerLabel: t('tasks.controllerLabel'),
    updatedLabel: t('tasks.updatedLabel'),
    briefFallback: t('tasks.briefFallback'),
    timelineTitle: t('tasks.timelineTitle'),
    timelineEmptyDetail: t('tasks.timelineEmptyDetail'),
    blueprintTitle: t('tasks.blueprintTitle'),
    blueprintEmpty: t('tasks.blueprintEmpty'),
    blueprintEntryLabel: t('tasks.blueprintEntryLabel'),
    blueprintControllerLabel: t('tasks.blueprintControllerLabel'),
    blueprintNodesLabel: t('tasks.blueprintNodesLabel'),
    blueprintEdgesLabel: t('tasks.blueprintEdgesLabel'),
    blueprintArtifactsLabel: t('tasks.blueprintArtifactsLabel'),
    stageRosterTitle: t('tasks.stageRosterTitle'),
    stageRosterDesiredLabel: t('tasks.stageRosterDesiredLabel'),
    stageRosterJoinedLabel: t('tasks.stageRosterJoinedLabel'),
    stageRosterRulesLabel: t('tasks.stageRosterRulesLabel'),
    stageRosterRulesKeepController: t('tasks.stageRosterRulesKeepController'),
    stageRosterRulesNone: t('tasks.stageRosterRulesNone'),
    conversationTitle: t('tasks.conversationTitle'),
    conversationEmpty: t('tasks.conversationEmpty'),
    progressTitle: t('tasks.progressTitle'),
    subtasksTitle: t('tasks.subtasksTitle'),
    subtaskFallbackType: t('tasks.subtaskFallbackType'),
    subtaskCloseAction: t('tasks.subtaskCloseAction'),
    subtaskArchiveAction: t('tasks.subtaskArchiveAction'),
    subtaskCancelAction: t('tasks.subtaskCancelAction'),
    executionTitle: t('tasks.executionTitle'),
    executionListLabel: t('tasks.executionListLabel'),
    executionEmpty: t('tasks.executionEmpty'),
    executionObserveAction: t('tasks.executionObserveAction'),
    executionObserveSuccess: t('tasks.executionObserveSuccess'),
    executionProbeAction: t('tasks.executionProbeAction'),
    executionProbeSuccess: t('tasks.executionProbeSuccess'),
    executionTailLabel: t('tasks.executionTailLabel'),
    executionTailEmpty: t('tasks.executionTailEmpty'),
    executionTailUnavailable: t('tasks.executionTailUnavailable'),
    executionTailAction: t('tasks.executionTailAction'),
    executionTailRefreshAction: t('tasks.executionTailRefreshAction'),
    executionTailLiveLabel: t('tasks.executionTailLiveLabel'),
    executionTailSnapshotLabel: t('tasks.executionTailSnapshotLabel'),
    executionTailUpdatedLabel: t('tasks.executionTailUpdatedLabel'),
    executionTailPollingLabel: t('tasks.executionTailPollingLabel'),
    executionTextLabel: t('tasks.executionTextLabel'),
    executionTextPlaceholder: t('tasks.executionTextPlaceholder'),
    executionTextAction: t('tasks.executionTextAction'),
    executionInputSuccess: t('tasks.executionInputSuccess'),
    executionStopAction: t('tasks.executionStopAction'),
    executionChoiceLabel: t('tasks.executionChoiceLabel'),
    executionKeysLabel: t('tasks.executionKeysLabel'),
    executionCountUnit: t('tasks.executionCountUnit'),
    governanceActiveLabel: t('tasks.governanceActiveLabel'),
    governancePerAgentLabel: t('tasks.governancePerAgentLabel'),
    governanceMemoryLabel: t('tasks.governanceMemoryLabel'),
    governanceLoadLabel: t('tasks.governanceLoadLabel'),
    governancePressureLabel: t('tasks.governancePressureLabel'),
    governanceWarningsLabel: t('tasks.governanceWarningsLabel'),
    governanceExecutionDetailsLabel: t('tasks.governanceExecutionDetailsLabel'),
    governanceAssigneeLabel: t('tasks.governanceAssigneeLabel'),
    runtimeRecoveryTitle: t('tasks.runtimeRecoveryTitle'),
    runtimeDiagnosisAction: t('tasks.runtimeDiagnosisAction'),
    runtimeRestartAction: t('tasks.runtimeRestartAction'),
    actionsTitle: t('tasks.actionsTitle'),
    actorLabel: t('tasks.actorLabel'),
    noteLabel: t('tasks.noteLabel'),
    notePlaceholder: t('tasks.notePlaceholder'),
    advanceAction: t('tasks.advanceAction'),
    approveAction: t('tasks.approveAction'),
    rejectAction: t('tasks.rejectAction'),
    confirmApproveAction: t('tasks.confirmApproveAction'),
    confirmRejectAction: t('tasks.confirmRejectAction'),
    pauseAction: t('tasks.pauseAction'),
    resumeAction: t('tasks.resumeAction'),
    cancelAction: t('tasks.cancelAction'),
    unblockAction: t('tasks.unblockAction'),
    forceAdvanceAction: t('tasks.forceAdvanceAction'),
    emptyTitle: t('tasks.emptyTitle'),
    emptySummary: t('tasks.emptySummary'),
    stats: {
      currentMatches: t('tasks.stats.currentMatches'),
      awaitingReview: t('tasks.stats.awaitingReview'),
      currentFocus: t('tasks.stats.currentFocus'),
    },
  };
}

export function useReviewsPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('reviews.kicker'),
    title: t('reviews.title'),
    summary: t('reviews.summary'),
    workbenchTitle: t('reviews.workbenchTitle'),
    workbenchSummary: t('reviews.workbenchSummary'),
    filterAction: t('reviews.filterAction'),
    clearFiltersAction: t('reviews.clearFiltersAction'),
    applyFiltersAction: t('reviews.applyFiltersAction'),
    detailAction: t('reviews.detailAction'),
    detailDialogLabel: t('reviews.detailDialogLabel'),
    detailDialogTitle: t('reviews.detailDialogTitle'),
    filterSectionLabels: {
      priority: t('reviews.filterSectionLabels.priority'),
      gate: t('reviews.filterSectionLabels.gate'),
      creator: t('reviews.filterSectionLabels.creator'),
    },
    activeFilterPrefix: t('reviews.activeFilterPrefix'),
    metricLabels: {
      queue: t('reviews.metricLabels.queue'),
      highestRisk: t('reviews.metricLabels.highestRisk'),
      defaultAction: t('reviews.metricLabels.defaultAction'),
    },
    metricValues: {
      highestRisk: t('reviews.metricValues.highestRisk'),
      normal: t('reviews.metricValues.normal'),
      defaultAction: t('reviews.metricValues.defaultAction'),
    },
    queueKicker: t('reviews.queueKicker'),
    queueTitle: t('reviews.queueTitle'),
    queueCountUnit: t('reviews.queueCountUnit'),
    queueFallbackSummary: t('reviews.queueFallbackSummary'),
    queueFallbackImpactPrefix: t('reviews.queueFallbackImpactPrefix'),
    queueFallbackImpactSuffix: t('reviews.queueFallbackImpactSuffix'),
    workspaceKicker: t('reviews.workspaceKicker'),
    workspaceTitle: t('reviews.workspaceTitle'),
    gateLabel: t('reviews.gateLabel'),
    impactLabel: t('reviews.impactLabel'),
    contextTitle: t('reviews.contextTitle'),
    progressTitle: t('reviews.progressTitle'),
    noteLabel: t('reviews.noteLabel'),
    notePlaceholder: t('reviews.notePlaceholder'),
    rejectAction: t('reviews.rejectAction'),
    approveAction: t('reviews.approveAction'),
    emptyTitle: t('reviews.emptyTitle'),
    emptySummary: t('reviews.emptySummary'),
    queueScopes: {
      high: t('reviews.queueScopes.high'),
    },
    tableHeaders: {
      task: t('reviews.tableHeaders.task'),
      gate: t('reviews.tableHeaders.gate'),
      priority: t('reviews.tableHeaders.priority'),
      wait: t('reviews.tableHeaders.wait'),
    },
    liveApiNotice: t('reviews.liveApiNotice'),
  };
}

export function useAgentsPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('agents.kicker'),
    title: t('agents.title'),
    summary: t('agents.summary'),
    metrics: {
      activeTasks: t('agents.metrics.activeTasks'),
      activeAgents: t('agents.metrics.activeAgents'),
      totalAgents: t('agents.metrics.totalAgents'),
      onlineAgents: t('agents.metrics.onlineAgents'),
      staleAgents: t('agents.metrics.staleAgents'),
      disconnectedAgents: t('agents.metrics.disconnectedAgents'),
      busyCraftsmen: t('agents.metrics.busyCraftsmen'),
    },
    channelSummaryTitle: t('agents.channelSummaryTitle'),
    hostSummaryTitle: t('agents.hostSummaryTitle'),
    channelDetailTitle: t('agents.channelDetailTitle'),
    channelTimelineTitle: t('agents.channelTimelineTitle'),
    channelSignalsTitle: t('agents.channelSignalsTitle'),
    runtimeSummaryTitle: t('agents.runtimeSummaryTitle'),
    runtimeTitle: t('agents.tmuxRuntimeTitle'),
    filtersTitle: t('agents.filtersTitle'),
    filterLabels: {
      all: t('agents.filterLabels.all'),
      busy: t('agents.filterLabels.busy'),
      online: t('agents.filterLabels.online'),
      stale: t('agents.filterLabels.stale'),
      disconnected: t('agents.filterLabels.disconnected'),
      offline: t('agents.filterLabels.offline'),
    },
    selectabilityFilterLabel: t('agents.selectabilityFilterLabel'),
    selectabilityFilterLabels: {
      all: t('agents.selectabilityFilterLabels.all'),
      selectable: t('agents.selectabilityFilterLabels.selectable'),
      restricted: t('agents.selectabilityFilterLabels.restricted'),
    },
    agentListTitle: t('agents.agentListTitle'),
    craftsmenTitle: t('agents.craftsmenTitle'),
    emptyAgents: t('agents.emptyAgents'),
    emptyCraftsmen: t('agents.emptyCraftsmen'),
    roleLabel: t('agents.roleLabel'),
    channelLabel: t('agents.channelLabel'),
    hostLabel: t('agents.hostLabel'),
    inventorySourcesLabel: t('agents.inventorySourcesLabel'),
    modelLabel: t('agents.modelLabel'),
    presenceLabel: t('agents.presenceLabel'),
    presenceReasonLabel: t('agents.presenceReasonLabel'),
    selectabilityLabel: t('agents.selectabilityLabel'),
    selectabilityReasonLabel: t('agents.selectabilityReasonLabel'),
    selectabilityReasonLabels: {
      active_assignment: t('selectabilityReasons.active_assignment'),
      inventory_launchable: t('selectabilityReasons.inventory_launchable'),
      stale_observation: t('selectabilityReasons.stale_observation'),
      provider_disconnected: t('selectabilityReasons.provider_disconnected'),
      unbound_agent: t('selectabilityReasons.unbound_agent'),
      legacy_presence_gate: t('selectabilityReasons.legacy_presence_gate'),
      legacy_presence_ok: t('selectabilityReasons.legacy_presence_ok'),
      unknown: t('selectabilityReasons.unknown'),
    } satisfies AgentSelectabilityReasonLabels,
    accountLabel: t('agents.accountLabel'),
    statusLabel: t('agents.statusLabel'),
    lastSeenLabel: t('agents.lastSeenLabel'),
    loadLabel: t('agents.loadLabel'),
    taskCountLabel: t('agents.taskCountLabel'),
    subtaskCountLabel: t('agents.subtaskCountLabel'),
    currentTaskLabel: t('agents.currentTaskLabel'),
    runtimeSessionLabel: t('agents.runtimeSessionLabel'),
    runtimePanesLabel: t('agents.runtimePanesLabel'),
    runtimeReadyPanesLabel: t('agents.runtimeReadyPanesLabel'),
    runtimeActivePanesLabel: t('agents.runtimeActivePanesLabel'),
    runtimeRunningCraftsmenLabel: t('agents.runtimeRunningCraftsmenLabel'),
    runtimeFailedCraftsmenLabel: t('agents.runtimeFailedCraftsmenLabel'),
    readyLabel: t('agents.readyLabel'),
    paneLabel: t('agents.paneLabel'),
    commandLabel: t('agents.commandLabel'),
    tailPreviewLabel: t('agents.tailPreviewLabel'),
    loadTailAction: t('agents.loadTailAction'),
    loadingTailAction: t('agents.loadingTailAction'),
    continuityBackendLabel: t('agents.continuityBackendLabel'),
    resumeCapabilityLabel: t('agents.resumeCapabilityLabel'),
    sessionReferenceLabel: t('agents.sessionReferenceLabel'),
    identitySourceLabel: t('agents.identitySourceLabel'),
    identityPathLabel: t('agents.identityPathLabel'),
    observedAtLabel: t('agents.observedAtLabel'),
    recoveryModeLabel: t('agents.recoveryModeLabel'),
    emptyChannelDetail: t('agents.emptyChannelDetail'),
    emptyChannelHistory: t('agents.emptyChannelHistory'),
    emptyChannelSignals: t('agents.emptyChannelSignals'),
    emptyHostSummary: t('agents.emptyHostSummary'),
    emptyRuntime: t('agents.emptyTmuxRuntime'),
    workspace: {
      overviewKicker: t('agents.workspace.overviewKicker'),
      overviewTitle: t('agents.workspace.overviewTitle'),
      focusKicker: t('agents.workspace.focusKicker'),
      focusTitle: t('agents.workspace.focusTitle'),
      issueQueueKicker: t('agents.workspace.issueQueueKicker'),
      issueQueueTitle: t('agents.workspace.issueQueueTitle'),
      detailEntryKicker: t('agents.workspace.detailEntryKicker'),
      detailEntryTitle: t('agents.workspace.detailEntryTitle'),
      attentionLabel: t('agents.workspace.attentionLabel'),
      stableLabel: t('agents.workspace.stableLabel'),
      issueCountOpen: (count: number) => t('agents.workspace.issueCountOpen', { count }),
      issueCountStable: t('agents.workspace.issueCountStable'),
      channelFocusLabel: t('agents.workspace.channelFocusLabel'),
      channelFocusMessage: (channel: string) => t('agents.workspace.channelFocusMessage', { channel }),
      channelFocusEmpty: t('agents.workspace.channelFocusEmpty'),
      agentFocusLabel: t('agents.workspace.agentFocusLabel'),
      agentCriticalMessage: (agent: string) => t('agents.workspace.agentCriticalMessage', { agent }),
      agentStaleMessage: (agent: string) => t('agents.workspace.agentStaleMessage', { agent }),
      agentFocusEmpty: t('agents.workspace.agentFocusEmpty'),
      executionFocusLabel: t('agents.workspace.executionFocusLabel'),
      executionFailedMessage: (count: number) => t('agents.workspace.executionFailedMessage', { count }),
      executionReadyMessage: (ready: number, total: number) => t('agents.workspace.executionReadyMessage', { ready, total }),
      issueQueueEmpty: t('agents.workspace.issueQueueEmpty'),
      issueGroups: {
        channelHealth: t('agents.workspace.issueGroups.channelHealth'),
        agentCritical: t('agents.workspace.issueGroups.agentCritical'),
        agentStale: t('agents.workspace.issueGroups.agentStale'),
        craftsmanFailed: t('agents.workspace.issueGroups.craftsmanFailed'),
        runtimeUnhealthy: t('agents.workspace.issueGroups.tmuxUnhealthy'),
        channelSummary: (count: number) => t('agents.workspace.issueGroups.channelSummary', { count }),
        channelDetail: (channel: string, presence: string, transportErrors: number) =>
          t('agents.workspace.issueGroups.channelDetail', { channel, presence, transportErrors }),
        agentCriticalSummary: (count: number) => t('agents.workspace.issueGroups.agentCriticalSummary', { count }),
        agentCriticalDetail: (agent: string) => t('agents.workspace.issueGroups.agentCriticalDetail', { agent }),
        agentStaleSummary: (count: number) => t('agents.workspace.issueGroups.agentStaleSummary', { count }),
        agentStaleDetail: (agent: string) => t('agents.workspace.issueGroups.agentStaleDetail', { agent }),
        craftsmanFailedSummary: (count: number) => t('agents.workspace.issueGroups.craftsmanFailedSummary', { count }),
        craftsmanFailedDetail: (craftsman: string) => t('agents.workspace.issueGroups.craftsmanFailedDetail', { craftsman }),
        runtimeUnhealthySummary: (count: number) => t('agents.workspace.issueGroups.tmuxUnhealthySummary', { count }),
        runtimeUnhealthyDetail: (agent: string) => t('agents.workspace.issueGroups.tmuxUnhealthyDetail', { agent }),
      },
      signalNotes: {
        channels: (count: number) => t('agents.workspace.signalNotes.channels', { count }),
        craftsmen: (count: number) => t('agents.workspace.signalNotes.craftsmen', { count }),
        onlineAgents: (count: number) => t('agents.workspace.signalNotes.onlineAgents', { count }),
        readyPanes: (ready: number, total: number) => t('agents.workspace.signalNotes.readyPanes', { ready, total }),
      },
      signalLabels: {
        channelIssues: t('agents.workspace.signalLabels.channelIssues'),
        craftsmanFailures: t('agents.workspace.signalLabels.craftsmanFailures'),
        agentIssues: t('agents.workspace.signalLabels.agentIssues'),
        runtimeUnready: t('agents.workspace.signalLabels.tmuxUnready'),
      },
      axis: {
        agentAction: t('agents.workspace.axis.agentAction'),
        agentSummary: t('agents.workspace.axis.agentSummary'),
        channelAction: t('agents.workspace.axis.channelAction'),
        channelSummary: t('agents.workspace.axis.channelSummary'),
        executionAction: t('agents.workspace.axis.executionAction'),
        executionSummary: t('agents.workspace.axis.executionSummary'),
      },
      drawers: {
        agentLabel: t('agents.workspace.drawers.agentLabel'),
        agentTitle: t('agents.workspace.drawers.agentTitle'),
        channelLabel: t('agents.workspace.drawers.channelLabel'),
        channelTitle: t('agents.workspace.drawers.channelTitle'),
        executionLabel: t('agents.workspace.drawers.executionLabel'),
        executionTitle: t('agents.workspace.drawers.executionTitle'),
      },
      tabs: {
        summary: t('agents.workspace.tabs.summary'),
        signals: t('agents.workspace.tabs.signals'),
        history: t('agents.workspace.tabs.history'),
      },
    },
  };
}

export function useTodosPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('todos.kicker'),
    title: t('todos.title'),
    summary: t('todos.summary'),
    inputLabel: t('todos.inputLabel'),
    inputPlaceholder: t('todos.inputPlaceholder'),
    projectLabel: t('todos.projectLabel'),
    noProjectOption: t('todos.noProjectOption'),
    dueLabel: t('todos.dueLabel'),
    tagsLabel: t('todos.tagsLabel'),
    tagsPlaceholder: t('todos.tagsPlaceholder'),
    createAction: t('todos.createAction'),
    filters: {
      all: t('todos.filters.all'),
      pending: t('todos.filters.pending'),
      done: t('todos.filters.done'),
    },
    projectFilterLabel: t('todos.projectFilterLabel'),
    allProjectsOption: t('todos.allProjectsOption'),
    emptyTitle: t('todos.emptyTitle'),
    promoteAction: t('todos.promoteAction'),
    deleteAction: t('todos.deleteAction'),
    doneAction: t('todos.doneAction'),
    reopenAction: t('todos.reopenAction'),
    promotedPrefix: t('todos.promotedPrefix'),
  };
}

export function useArchivePageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('archive.kicker'),
    title: t('archive.title'),
    summary: t('archive.summary'),
    filters: {
      all: t('archive.filters.all'),
      pending: t('archive.filters.pending'),
      failed: t('archive.filters.failed'),
      completed: t('archive.filters.completed'),
    },
    taskIdLabel: t('archive.taskIdLabel'),
    detailTitle: t('archive.detailTitle'),
    emptyTitle: t('archive.emptyTitle'),
    payloadTitle: t('archive.payloadTitle'),
    confirmAction: t('archive.confirmAction'),
    retryAction: t('archive.retryAction'),
    requestedAtLabel: t('archive.requestedAtLabel'),
    completedAtLabel: t('archive.completedAtLabel'),
    targetPathLabel: t('archive.targetPathLabel'),
  };
}

export function useTemplatesPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('templates.kicker'),
    title: t('templates.title'),
    summary: t('templates.summary'),
    listTitle: t('templates.listTitle'),
    detailTitle: t('templates.detailTitle'),
    governanceLabel: t('templates.governanceLabel'),
    teamLabel: t('templates.teamLabel'),
    createAction: t('templates.createAction'),
    createIdLabel: t('templates.createIdLabel'),
    createNameLabel: t('templates.createNameLabel'),
    createIdPlaceholder: t('templates.createIdPlaceholder'),
    createNamePlaceholder: t('templates.createNamePlaceholder'),
    createHint: t('templates.createHint'),
    addRoleAction: t('templates.addRoleAction'),
    deleteRoleAction: t('templates.deleteRoleAction'),
    teamRoleSelectLabel: t('templates.teamRoleSelectLabel'),
    descriptionLabel: t('templates.descriptionLabel'),
    memberKindLabel: t('templates.memberKindLabel'),
    modelPreferenceLabel: t('templates.modelPreferenceLabel'),
    suggestedAgentsLabel: t('templates.suggestedAgentsLabel'),
    duplicateIdLabel: t('templates.duplicateIdLabel'),
    saveAction: t('templates.saveAction'),
    savingAction: t('templates.savingAction'),
    duplicateAction: t('templates.duplicateAction'),
    validateAction: t('templates.validateAction'),
    validationPassed: t('templates.validationPassed'),
    compatibilityTitle: t('templates.compatibilityTitle'),
    missingSuggestedLabel: t('templates.missingSuggestedLabel'),
    unavailableSuggestedLabel: t('templates.unavailableSuggestedLabel'),
    compatibilitySaveBlocked: t('templates.compatibilitySaveBlocked'),
    controllerSaveBlocked: t('templates.controllerSaveBlocked'),
    missingControllerLabel: t('templates.missingControllerLabel'),
    duplicateControllersLabel: t('templates.duplicateControllersLabel'),
    stagesTitle: t('templates.stagesTitle'),
    addStageAction: t('templates.addStageAction'),
    deleteStageAction: t('templates.deleteStageAction'),
    moveStageUpAction: t('templates.moveStageUpAction'),
    moveStageDownAction: t('templates.moveStageDownAction'),
    stageModeLabel: t('templates.stageModeLabel'),
    stageGateLabel: t('templates.stageGateLabel'),
    stageRejectTargetLabel: t('templates.stageRejectTargetLabel'),
    stageNoRejectTargetLabel: t('templates.stageNoRejectTargetLabel'),
    stageApproverLabel: t('templates.stageApproverLabel'),
    stageRequiredLabel: t('templates.stageRequiredLabel'),
    stageTimeoutLabel: t('templates.stageTimeoutLabel'),
    graphTitle: t('templates.graphTitle'),
    graphNodesLabel: t('templates.graphNodesLabel'),
    graphEdgesLabel: t('templates.graphEdgesLabel'),
    graphOpenEditorAction: t('templates.graphOpenEditorAction'),
    graphEditorSummary: t('templates.graphEditorSummary'),
    graphBackAction: t('templates.graphBackAction'),
    graphSaveAction: t('templates.graphSaveAction'),
    graphSaveBlocked: t('templates.graphSaveBlocked'),
    graphLoadingTitle: t('templates.graphLoadingTitle'),
    graphUnavailableTitle: t('templates.graphUnavailableTitle'),
    graphToolsTitle: t('templates.graphToolsTitle'),
    graphToolsHint: t('templates.graphToolsHint'),
    graphAddNodeAction: t('templates.graphAddNodeAction'),
    graphTidyLayoutAction: t('templates.graphTidyLayoutAction'),
    graphInspectorTitle: t('templates.graphInspectorTitle'),
    graphInspectorEmpty: t('templates.graphInspectorEmpty'),
    graphEntryLabel: t('templates.graphEntryLabel'),
    graphEntryToggleLabel: t('templates.graphEntryToggleLabel'),
    graphNodeNameLabel: t('templates.graphNodeNameLabel'),
    graphExecutionKindLabel: t('templates.graphExecutionKindLabel'),
    graphGateTypeLabel: t('templates.graphGateTypeLabel'),
    graphRosterRolesLabel: t('templates.graphRosterRolesLabel'),
    graphRosterKeepControllerLabel: t('templates.graphRosterKeepControllerLabel'),
    graphNextStageLabel: t('templates.graphNextStageLabel'),
    graphNoNextStageLabel: t('templates.graphNoNextStageLabel'),
    graphRejectTargetLabel: t('templates.graphRejectTargetLabel'),
    graphNoRejectTargetLabel: t('templates.graphNoRejectTargetLabel'),
    graphAddAdvanceEdgeAction: t('templates.graphAddAdvanceEdgeAction'),
    graphAddRejectEdgeAction: t('templates.graphAddRejectEdgeAction'),
    graphDeleteNodeAction: t('templates.graphDeleteNodeAction'),
    graphDeleteEdgeAction: t('templates.graphDeleteEdgeAction'),
    graphEdgeKindLabel: t('templates.graphEdgeKindLabel'),
    graphEdgeKindOptions: {
      advance: t('templates.graphEdgeKindOptions.advance'),
      reject: t('templates.graphEdgeKindOptions.reject'),
    },
    graphExecutionKindOptions: {
      default: t('templates.graphExecutionKindOptions.default'),
      citizen_discuss: t('templates.graphExecutionKindOptions.citizenDiscuss'),
      citizen_execute: t('templates.graphExecutionKindOptions.citizenExecute'),
      human_approval: t('templates.graphExecutionKindOptions.humanApproval'),
      craftsman_dispatch: t('templates.graphExecutionKindOptions.craftsmanDispatch'),
    },
    graphGateTypeOptions: {
      none: t('templates.graphGateTypeOptions.none'),
      command: t('templates.graphGateTypeOptions.command'),
      approval: t('templates.graphGateTypeOptions.approval'),
      archon_review: t('templates.graphGateTypeOptions.archonReview'),
      quorum: t('templates.graphGateTypeOptions.quorum'),
      all_subtasks_done: t('templates.graphGateTypeOptions.allSubtasksDone'),
      auto_timeout: t('templates.graphGateTypeOptions.autoTimeout'),
    },
    graphNodeSummary: (executionKind: string, gateType: string) => t('templates.graphNodeSummary', { executionKind, gateType }),
    graphValidationErrors: {
      missingNode: t('templates.graphValidationErrors.missingNode'),
      missingEntry: t('templates.graphValidationErrors.missingEntry'),
      unknownEntry: (entryId: string) => t('templates.graphValidationErrors.unknownEntry', { entryId }),
      unknownEdgeSource: (nodeId: string) => t('templates.graphValidationErrors.unknownEdgeSource', { nodeId }),
      unknownEdgeTarget: (nodeId: string) => t('templates.graphValidationErrors.unknownEdgeTarget', { nodeId }),
      advanceNotForward: (from: string, to: string) => t('templates.graphValidationErrors.advanceNotForward', { from, to }),
      rejectNotBackward: (from: string, to: string) => t('templates.graphValidationErrors.rejectNotBackward', { from, to }),
      multipleAdvanceOutgoing: (nodeId: string) => t('templates.graphValidationErrors.multipleAdvanceOutgoing', { nodeId }),
      multipleAdvanceIncoming: (nodeId: string) => t('templates.graphValidationErrors.multipleAdvanceIncoming', { nodeId }),
      multipleRejectOutgoing: (nodeId: string) => t('templates.graphValidationErrors.multipleRejectOutgoing', { nodeId }),
    },
    emptyTitle: t('templates.emptyTitle'),
    removeSuggestedAgentAria: (agentId: string) => t('templates.removeSuggestedAgentAria', { agentId }),
    stageNameAria: (stageId: string) => t('templates.stageNameAria', { stageId }),
    stageDeleteAria: (stageId: string) => t('templates.stageDeleteAria', { stageId }),
    stageMoveUpAria: (stageId: string) => t('templates.stageMoveUpAria', { stageId }),
    stageMoveDownAria: (stageId: string) => t('templates.stageMoveDownAria', { stageId }),
    removeRoleAria: (role: string) => t('templates.removeRoleAria', { role }),
  };
}

export function useSettingsPageCopy() {
  const { t } = useTranslation();

  return {
    sectionLabel: t('shell.nav.settings.label'),
    kicker: t('settings.kicker'),
    title: t('settings.title'),
    summary: t('settings.summary'),
    gatewayKicker: t('settings.gatewayKicker'),
    gatewayTitle: t('settings.gatewayTitle'),
    endpointLabel: t('settings.endpointLabel'),
    tokenLabel: t('settings.tokenLabel'),
    tokenPlaceholder: t('settings.tokenPlaceholder'),
    tokenHideLabel: t('settings.tokenHideLabel'),
    tokenShowLabel: t('settings.tokenShowLabel'),
    refreshKicker: t('settings.refreshKicker'),
    refreshTitle: t('settings.refreshTitle'),
    refreshLabel: t('settings.refreshLabel'),
    pauseLabel: t('settings.pauseLabel'),
    appearanceKicker: t('settings.appearanceKicker'),
    appearanceTitle: t('settings.appearanceTitle'),
    appearanceDescriptions: {
      light: t('settings.appearanceDescriptions.light'),
      dark: t('settings.appearanceDescriptions.dark'),
      system: t('settings.appearanceDescriptions.system'),
    },
    appearanceLabels: {
      light: t('settings.appearanceLabels.light'),
      dark: t('settings.appearanceLabels.dark'),
      system: t('settings.appearanceLabels.system'),
    },
    languageKicker: t('settings.languageKicker'),
    languageTitle: t('settings.languageTitle'),
    saveAction: t('settings.saveAction'),
    testAction: t('settings.testAction'),
    cleanupAction: t('settings.cleanupAction'),
    cleanupSuccess: (count: number) => t('settings.cleanupSuccess', { count }),
    healthSuccess: t('settings.healthSuccess'),
    healthFailureFallback: t('settings.healthFailureFallback'),
    healthLoading: t('settings.healthLoading'),
    accessKicker: t('settings.accessKicker'),
    accessTitle: t('settings.accessTitle'),
    accessSummary: t('settings.accessSummary'),
    accountKicker: t('settings.accountKicker'),
    accountTitle: t('settings.accountTitle'),
    accountSummary: t('settings.accountSummary'),
    sessionLabels: {
      actor: t('settings.sessionLabels.actor'),
      role: t('settings.sessionLabels.role'),
      method: t('settings.sessionLabels.method'),
    },
    roleLabels: {
      admin: t('settings.roleLabels.admin'),
      member: t('settings.roleLabels.member'),
    },
    adminOnlyNotice: t('settings.adminOnlyNotice'),
    reloadAccountsAction: t('settings.reloadAccountsAction'),
    loadingAccounts: t('settings.loadingAccounts'),
    noAccounts: t('settings.noAccounts'),
    createUserTitle: t('settings.createUserTitle'),
    usernameLabel: t('settings.usernameLabel'),
    passwordLabel: t('settings.passwordLabel'),
    createUserAction: t('settings.createUserAction'),
    resetPasswordAction: t('settings.resetPasswordAction'),
    disableUserAction: t('settings.disableUserAction'),
    bindIdentityTitle: t('settings.bindIdentityTitle'),
    providerLabel: t('settings.providerLabel'),
    externalUserIdLabel: t('settings.externalUserIdLabel'),
    bindIdentityAction: t('settings.bindIdentityAction'),
    userIdentityEmpty: t('settings.userIdentityEmpty'),
    enabledLabel: t('settings.enabledLabel'),
    disabledLabel: t('settings.disabledLabel'),
    operationMessages: {
      loadFailedTitle: t('settings.operationMessages.loadFailedTitle'),
      createSuccessTitle: t('settings.operationMessages.createSuccessTitle'),
      createSuccessDetail: (username: string) => t('settings.operationMessages.createSuccessDetail', { username }),
      createFailedTitle: t('settings.operationMessages.createFailedTitle'),
      passwordSuccessTitle: t('settings.operationMessages.passwordSuccessTitle'),
      passwordSuccessDetail: (username: string) => t('settings.operationMessages.passwordSuccessDetail', { username }),
      passwordFailedTitle: t('settings.operationMessages.passwordFailedTitle'),
      disableSuccessTitle: t('settings.operationMessages.disableSuccessTitle'),
      disableSuccessDetail: (username: string) => t('settings.operationMessages.disableSuccessDetail', { username }),
      disableFailedTitle: t('settings.operationMessages.disableFailedTitle'),
      identitySuccessTitle: t('settings.operationMessages.identitySuccessTitle'),
      identitySuccessDetail: (username: string) => t('settings.operationMessages.identitySuccessDetail', { username }),
      identityFailedTitle: t('settings.operationMessages.identityFailedTitle'),
    },
  };
}
