import { useTranslation } from 'react-i18next';
import type { AgentSelectabilityReasonLabels } from '@/lib/agentSelectability';

export function useShellCopy() {
  const { t } = useTranslation();

  return {
    brandName: t('shell.brandName'),
    brandSystemName: t('shell.brandSystemName'),
    brandSignature: t('shell.brandSignature'),
    workspaceLabel: t('shell.workspaceLabel'),
    systemClockLabel: t('shell.systemClockLabel'),
    commandLabel: t('shell.commandLabel'),
    statusLabel: t('shell.statusLabel'),
    statusValue: t('shell.statusValue'),
    manifesto: t('shell.manifesto', { returnObjects: true }) as string[],
    footerProjectLabel: t('shell.footerProjectLabel'),
    footerProjectValue: t('shell.footerProjectValue'),
    footerRevisionLabel: t('shell.footerRevisionLabel'),
    footerRevisionValue: t('shell.footerRevisionValue'),
    footerStatusLabel: t('shell.footerStatusLabel'),
    footerStatusValue: t('shell.footerStatusValue'),
    footerTagline: t('shell.footerTagline'),
    footerVersion: t('shell.footerVersion'),
    railStatement: t('shell.railStatement'),
    railSummary: t('shell.railSummary'),
    navItems: [
      { to: '/', key: 'overview', label: t('shell.nav.overview.label'), hint: t('shell.nav.overview.hint') },
      { to: '/projects', key: 'projects', label: t('shell.nav.projects.label'), hint: t('shell.nav.projects.hint') },
      { to: '/agents', key: 'agents', label: t('shell.nav.agents.label'), hint: t('shell.nav.agents.hint') },
      { to: '/bridges', key: 'bridges', label: t('shell.nav.bridges.label'), hint: t('shell.nav.bridges.hint') },
      { to: '/todos', key: 'todos', label: t('shell.nav.todos.label'), hint: t('shell.nav.todos.hint') },
      { to: '/archive', key: 'archive', label: t('shell.nav.archive.label'), hint: t('shell.nav.archive.hint') },
      { to: '/templates', key: 'templates', label: t('shell.nav.templates.label'), hint: t('shell.nav.templates.hint') },
      { to: '/tasks/new', key: 'create', label: t('shell.nav.create.label'), hint: t('shell.nav.create.hint') },
      { to: '/reviews', key: 'reviews', label: t('shell.nav.reviews.label'), hint: t('shell.nav.reviews.hint') },
      { to: '/settings', key: 'settings', label: t('shell.nav.settings.label'), hint: t('shell.nav.settings.hint') },
    ],
  };
}

export function usePageMetaCopy() {
  const { t } = useTranslation();

  return {
    '/': { title: t('pageMeta.home.title') },
    '/board': { title: t('pageMeta.board.title') },
    '/projects': { title: t('pageMeta.projects.title') },
    '/workspace/bootstrap': { title: t('pageMeta.workspaceBootstrap.title') },
    '/tasks': { title: t('pageMeta.tasks.title') },
    '/agents': { title: t('pageMeta.agents.title') },
    '/bridges': { title: t('pageMeta.bridges.title') },
    '/todos': { title: t('pageMeta.todos.title') },
    '/archive': { title: t('pageMeta.archive.title') },
    '/templates': { title: t('pageMeta.templates.title') },
    '/tasks/new': { title: t('pageMeta.createTask.title') },
    '/reviews': { title: t('pageMeta.reviews.title') },
    '/settings': { title: t('pageMeta.settings.title') },
  } as const;
}

export function useProjectWorkspaceCopy() {
  return {
    ariaLabel: 'Project workspace',
    items: [
      { to: '/projects/:projectId', label: 'Overview', end: true },
      { to: '/projects/:projectId/work', label: 'Current Work' },
      { to: '/projects/:projectId/brain', label: 'Brain' },
      { to: '/projects/:projectId/knowledge', label: 'Knowledge' },
      { to: '/projects/:projectId/archive', label: 'Archive' },
      { to: '/projects/:projectId/operator', label: 'Operator' },
    ],
  };
}

export function useDashboardHomeCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('home.kicker'),
    title: t('home.title'),
    summary: t('home.summary'),
    slogan: t('home.slogan'),
    heroStatusLabel: t('home.heroStatusLabel'),
    heroStackLabels: {
      pending: t('home.heroStackLabels.pending'),
      active: t('home.heroStackLabels.active'),
      governance: t('home.heroStackLabels.governance'),
    },
    heroBriefs: {
      pending: (count: number, title: string) => t('home.heroBriefs.pending', { count, title }),
      idle: () => t('home.heroBriefs.idle'),
      active: (count: number, executions: number) => t('home.heroBriefs.active', { count, executions }),
      governance: (runtime: string, load: string) => t('home.heroBriefs.governance', { runtime, load }),
    },
    sectionLabels: {
      agora: t('home.sectionLabels.agora'),
      archon: t('home.sectionLabels.archon'),
      pipeline: t('home.sectionLabels.pipeline'),
    },
    commandAuthorityLabel: t('home.commandAuthorityLabel'),
    pendingResolutionLabel: t('home.pendingResolutionLabel'),
    executionLabel: t('home.executionLabel'),
    topologyLabel: t('home.topologyLabel'),
    terminalLabel: t('home.terminalLabel'),
    systemLoadLabel: t('home.systemLoadLabel'),
    architectureLabel: t('home.architectureLabel'),
    primaryAction: t('home.primaryAction'),
    secondaryAction: t('home.secondaryAction'),
    tertiaryAction: t('home.tertiaryAction'),
    syncErrorMessage: t('home.syncErrorMessage'),
    pulseKicker: t('home.pulseKicker'),
    pulseTitle: t('home.pulseTitle'),
    pulseStatusLoading: t('home.pulseStatusLoading'),
    pulseStatusReady: t('home.pulseStatusReady'),
    pulseOrbitLabels: {
      left: t('home.pulseOrbitLabels.left'),
      right: t('home.pulseOrbitLabels.right'),
      bottom: t('home.pulseOrbitLabels.bottom'),
    },
    pulseItemLabels: {
      running: t('home.pulseItems.running.label'),
      waiting: t('home.pulseItems.waiting.label'),
      latestCompleted: t('home.pulseItems.latestCompleted.label'),
    },
    sideNotes: [
      {
        kicker: t('home.sideNotes.brand.kicker'),
        title: t('home.sideNotes.brand.title'),
        body: t('home.sideNotes.brand.body'),
      },
      {
        kicker: t('home.sideNotes.promise.kicker'),
        title: t('home.sideNotes.promise.title'),
        body: t('home.sideNotes.promise.body'),
      },
    ],
    metricLabels: {
      active: t('home.metrics.activeLabel'),
      waiting: t('home.metrics.waitingLabel'),
      participants: t('home.metrics.participantsLabel'),
      latestCompleted: t('home.metrics.latestCompletedLabel'),
      activeExecutions: t('home.metrics.activeExecutionsLabel'),
      hostLoad: t('home.metrics.hostLoadLabel'),
    },
    metricNotes: {
      active: t('home.metrics.activeNote'),
      waiting: t('home.metrics.waitingNote'),
      participants: t('home.metrics.participantsNote'),
      latestCompleted: t('home.metrics.latestCompletedNote'),
      activeExecutions: t('home.metrics.activeExecutionsNote'),
      hostLoad: t('home.metrics.hostLoadNote'),
    },
    latestCompletedFallback: t('home.latestCompletedFallback'),
    feedKicker: t('home.feedKicker'),
    feedTitle: t('home.feedTitle'),
    feedAction: t('home.feedAction'),
    feedEmpty: t('home.feedEmpty'),
    emptyTaskDescription: t('home.emptyTaskDescription'),
    fallbackDecisionStage: t('home.fallbackDecisionStage'),
    reviewKicker: t('home.reviewKicker'),
    reviewTitle: t('home.reviewTitle'),
    reviewCountUnit: t('home.reviewCountUnit'),
    reviewDescriptionPrefix: t('home.reviewDescriptionPrefix'),
    reviewDeck: {
      previous: t('home.reviewDeck.previous'),
      next: t('home.reviewDeck.next'),
      position: t('home.reviewDeck.position'),
    },
    principleKicker: t('home.principleKicker'),
    principleTitle: t('home.principleTitle'),
    principleBullets: t('home.principleBullets', { returnObjects: true }) as string[],
    resolutionTitle: t('home.resolutionTitle'),
    resolutionSummary: t('home.resolutionSummary'),
    resolutionEmptyTitle: t('home.resolutionEmptyTitle'),
    resolutionEmptySummary: t('home.resolutionEmptySummary'),
    resolutionEmptyValue: t('home.resolutionEmptyValue'),
    resolutionMeta: {
      gate: t('home.resolutionMeta.gate'),
      stage: t('home.resolutionMeta.stage'),
    },
    resolutionFallbacks: {
      gate: t('home.resolutionFallbacks.gate'),
      stage: t('home.resolutionFallbacks.stage'),
      summary: t('home.resolutionFallbacks.summary'),
    },
    resolutionActions: {
      authorize: t('home.resolutionActions.authorize'),
      veto: t('home.resolutionActions.veto'),
      synthesize: t('home.resolutionActions.synthesize'),
    },
    resolutionReadOnlyNotice: t('home.resolutionReadOnlyNotice'),
    terminalStatusPrefix: t('home.terminalStatusPrefix'),
    terminalEmpty: t('home.terminalEmpty'),
    topologyHashLabel: t('home.topologyHashLabel'),
    topologyHashValue: t('home.topologyHashValue'),
    topologyNodes: t('home.topologyNodes', { returnObjects: true }) as string[],
    loadEstimateNote: t('home.loadEstimateNote'),
    governance: {
      kicker: t('home.governance.kicker'),
      title: t('home.governance.title'),
      hostMemory: t('home.governance.hostMemory'),
      pressureStatus: t('home.governance.pressureStatus'),
      runtimeStatus: t('home.governance.runtimeStatus'),
      escalationStatus: t('home.governance.escalationStatus'),
      warningsTitle: t('home.governance.warningsTitle'),
      executionDetailsTitle: t('home.governance.executionDetailsTitle'),
      assigneeTitle: t('home.governance.assigneeTitle'),
      emptyAssignee: t('home.governance.emptyAssignee'),
      emptyWarnings: t('home.governance.emptyWarnings'),
      emptyExecutionDetails: t('home.governance.emptyExecutionDetails'),
    },
    taskRailLabels: {
      selectedTask: t('home.taskRailLabels.selectedTask'),
      executionLoop: t('home.taskRailLabels.executionLoop'),
      runtimeLog: t('home.taskRailLabels.runtimeLog'),
      stageFallback: t('home.taskRailLabels.stageFallback'),
      logEmpty: t('home.taskRailLabels.logEmpty'),
      focusPrompt: t('home.taskRailLabels.focusPrompt'),
      taskEmpty: t('home.taskRailLabels.taskEmpty'),
    },
    proposalToneLabels: {
      constraint: t('home.proposalToneLabels.constraint'),
      optimize: t('home.proposalToneLabels.optimize'),
      observe: t('home.proposalToneLabels.observe'),
    },
    loadReadoutLabel: t('home.loadReadoutLabel'),
    constraintSignals: {
      waiting: t('home.constraintSignals.waiting'),
      stable: t('home.constraintSignals.stable'),
    },
  };
}

export function useBoardPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('board.kicker'),
    title: t('board.title'),
    summary: t('board.summary'),
    createAction: t('board.createAction'),
    projectFilterLabel: t('board.projectFilterLabel'),
    allProjectsOption: t('board.allProjectsOption'),
    unassignedProjectLabel: t('board.unassignedProjectLabel'),
    emptyTitle: t('board.emptyTitle'),
    emptySummary: t('board.emptySummary'),
    reviewFocusKicker: t('board.reviewFocusKicker'),
    columns: {
      pending: t('board.columns.pending'),
      inProgress: t('board.columns.inProgress'),
      gateWaiting: t('board.columns.gateWaiting'),
      completed: t('board.columns.completed'),
      interrupted: t('board.columns.interrupted'),
    },
  };
}

export function useCreateTaskPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('createTask.kicker'),
    title: t('createTask.title'),
    summary: t('createTask.summary'),
    titleLabel: t('createTask.titleLabel'),
    titlePlaceholder: t('createTask.titlePlaceholder'),
    projectLabel: t('createTask.projectLabel'),
    noProjectOption: t('createTask.noProjectOption'),
    descriptionLabel: t('createTask.descriptionLabel'),
    descriptionPlaceholder: t('createTask.descriptionPlaceholder'),
    typeLabel: t('createTask.typeLabel'),
    priorityLabel: t('createTask.priorityLabel'),
    globalSkillsLabel: t('createTask.globalSkillsLabel'),
    roleSkillsLabel: t('createTask.roleSkillsLabel'),
    noSkillsLabel: t('createTask.noSkillsLabel'),
    noSkillResultsLabel: t('createTask.noSkillResultsLabel'),
    noRoleSkillsSelectedLabel: t('createTask.noRoleSkillsSelectedLabel'),
    selectedSkillsCount: (count: number) => t('createTask.selectedSkillsCount', { count }),
    selectedSkillToggleHint: t('createTask.selectedSkillToggleHint'),
    deselectSkillTitle: (skillRef: string) => t('createTask.deselectSkillTitle', { skillRef }),
    openGlobalSkillsAction: t('createTask.openGlobalSkillsAction'),
    closeGlobalSkillsAction: t('createTask.closeGlobalSkillsAction'),
    globalSkillsSearchLabel: t('createTask.globalSkillsSearchLabel'),
    globalSkillsSearchPlaceholder: t('createTask.globalSkillsSearchPlaceholder'),
    globalSkillFilterLabels: {
      all: t('createTask.globalSkillFilterLabels.all'),
      selected: t('createTask.globalSkillFilterLabels.selected'),
      recommended: t('createTask.globalSkillFilterLabels.recommended'),
    },
    skillSignalLabels: {
      recommended: t('createTask.skillSignalLabels.recommended'),
      recent: t('createTask.skillSignalLabels.recent'),
    },
    openRoleSkillsAction: (role: string) => t('createTask.openRoleSkillsAction', { role }),
    closeRoleSkillsAction: (role: string) => t('createTask.closeRoleSkillsAction', { role }),
    roleSkillsSearchLabel: (role: string) => t('createTask.roleSkillsSearchLabel', { role }),
    roleSkillsSearchPlaceholder: t('createTask.roleSkillsSearchPlaceholder'),
    templateLabel: t('createTask.templateLabel'),
    teamLabel: t('createTask.teamLabel'),
    controllerLabel: t('createTask.controllerLabel'),
    ownerAccountLabel: t('createTask.ownerAccountLabel'),
    assigneeAccountLabel: t('createTask.assigneeAccountLabel'),
    approverAccountLabel: t('createTask.approverAccountLabel'),
    noHumanAuthorityOption: t('createTask.noHumanAuthorityOption'),
    threadLabel: t('createTask.threadLabel'),
    privateThreadLabel: t('createTask.privateThreadLabel'),
    teamSummary: t('createTask.teamSummary'),
    noAgentLabel: t('createTask.noAgentLabel'),
    restrictedSuggestedLabel: t('createTask.restrictedSuggestedLabel'),
    selectabilityReasonLabel: t('createTask.selectabilityReasonLabel'),
    selectabilityReasonLabels: {
      active_assignment: t('selectabilityReasons.active_assignment'),
      inventory_launchable: t('selectabilityReasons.inventory_launchable'),
      stale_observation: t('selectabilityReasons.stale_observation'),
      provider_disconnected: t('selectabilityReasons.provider_disconnected'),
      unbound_agent: t('selectabilityReasons.unbound_agent'),
      legacy_presence_gate: t('selectabilityReasons.legacy_presence_gate'),
      legacy_presence_ok: t('selectabilityReasons.legacy_presence_ok'),
      unknown: t('selectabilityReasons.unknown'),
    } satisfies AgentSelectabilityReasonLabels,
    sourceContextTitle: t('createTask.sourceContextTitle'),
    sourceContextSummary: t('createTask.sourceContextSummary'),
    sourceKindLabel: t('createTask.sourceKindLabel'),
    sourceTitleFieldLabel: t('createTask.sourceTitleFieldLabel'),
    sourceRefLabel: t('createTask.sourceRefLabel'),
    sourceTaskIdsLabel: t('createTask.sourceTaskIdsLabel'),
    sourceSnippetLabel: t('createTask.sourceSnippetLabel'),
    sourceKindLabels: {
      knowledge: t('createTask.sourceKindLabels.knowledge'),
      recap: t('createTask.sourceKindLabels.recap'),
      citizen: t('createTask.sourceKindLabels.citizen'),
    },
    submitAction: t('createTask.submitAction'),
    submittingAction: t('createTask.submittingAction'),
    backAction: t('createTask.backAction'),
    taskTypes: [
      { value: 'coding', label: t('createTask.taskType.coding') },
      { value: 'quick', label: t('createTask.taskType.quick') },
      { value: 'document', label: t('createTask.taskType.document') },
      { value: 'research', label: t('createTask.taskType.research') },
    ] as const,
  };
}

export function useProjectsPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('projectsPage.kicker'),
    title: t('projectsPage.title'),
    summary: t('projectsPage.summary'),
    poolTitle: t('projectsPage.poolTitle'),
    poolSummary: t('projectsPage.poolSummary'),
    countLabel: t('projectsPage.countLabel'),
    nomosLabel: t('projectsPage.nomosLabel'),
    noNomosLabel: t('projectsPage.noNomosLabel'),
    repoBoundLabel: t('projectsPage.repoBoundLabel'),
    noRepoLabel: t('projectsPage.noRepoLabel'),
    createToggleAction: t('projectsPage.createToggleAction'),
    nameLabel: t('projectsPage.nameLabel'),
    namePlaceholder: t('projectsPage.namePlaceholder'),
    summaryLabel: t('projectsPage.summaryLabel'),
    summaryPlaceholder: t('projectsPage.summaryPlaceholder'),
    adminAccountsLabel: t('projectsPage.adminAccountsLabel'),
    adminAccountsPlaceholder: t('projectsPage.adminAccountsPlaceholder'),
    memberAccountsLabel: t('projectsPage.memberAccountsLabel'),
    memberAccountsPlaceholder: t('projectsPage.memberAccountsPlaceholder'),
    searchLabel: t('projectsPage.searchLabel'),
    searchPlaceholder: t('projectsPage.searchPlaceholder'),
    sortLabel: t('projectsPage.sortLabel'),
    sortOptions: {
      updated: t('projectsPage.sortOptions.updated'),
      tasks: t('projectsPage.sortOptions.tasks'),
      todos: t('projectsPage.sortOptions.todos'),
      name: t('projectsPage.sortOptions.name'),
    },
    workspaceBootstrapTitle: t('projectsPage.workspaceBootstrapTitle'),
    workspaceBootstrapHintLabel: t('projectsPage.workspaceBootstrapHintLabel'),
    workspaceBootstrapSummary: t('projectsPage.workspaceBootstrapSummary'),
    workspaceBootstrapAction: t('projectsPage.workspaceBootstrapAction'),
    confirmAction: t('projectsPage.confirmAction'),
    creatingAction: t('projectsPage.creatingAction'),
    ownerLabel: t('projectsPage.ownerLabel'),
    ownerFallback: t('projectsPage.ownerFallback'),
    updatedLabel: t('projectsPage.updatedLabel'),
    repoPathLabel: t('projectsPage.repoPathLabel'),
    summaryFallback: t('projectsPage.summaryFallback'),
    selectProjectAction: (name: string) => t('projectsPage.selectProjectAction', { name }),
    openWorkspaceAction: t('projectsPage.openWorkspaceAction'),
    openProjectWorkspaceAction: t('projectsPage.openProjectWorkspaceAction'),
    openBrainAction: t('projectsPage.openBrainAction'),
    createTaskAction: t('projectsPage.createTaskAction'),
    currentWorkBriefTitle: t('projectsPage.currentWorkBriefTitle'),
    projectSurfacesBriefTitle: t('projectsPage.projectSurfacesBriefTitle'),
    previewLoadingTitle: t('projectsPage.previewLoadingTitle'),
    previewEmptyTitle: t('projectsPage.previewEmptyTitle'),
    emptyTasksTitle: t('projectsPage.emptyTasksTitle'),
    emptyTodosTitle: t('projectsPage.emptyTodosTitle'),
    statsLabels: {
      tasks: t('projectsPage.statsLabels.tasks'),
      activeTasks: t('projectsPage.statsLabels.activeTasks'),
      reviewTasks: t('projectsPage.statsLabels.reviewTasks'),
      pendingTodos: t('projectsPage.statsLabels.pendingTodos'),
      knowledge: t('projectsPage.statsLabels.knowledge'),
      citizens: t('projectsPage.statsLabels.citizens'),
    },
    metricValues: {
      tasks: (count: number) => t('projectsPage.metricValues.tasks', { count }),
      active: (count: number) => t('projectsPage.metricValues.active', { count }),
      review: (count: number) => t('projectsPage.metricValues.review', { count }),
      todos: (count: number) => t('projectsPage.metricValues.todos', { count }),
      tasksPending: t('projectsPage.metricValues.tasksPending'),
      activePending: t('projectsPage.metricValues.activePending'),
      reviewPending: t('projectsPage.metricValues.reviewPending'),
      todosPending: t('projectsPage.metricValues.todosPending'),
    },
    surfaceSignals: {
      index: (ready: boolean) => t('projectsPage.surfaceSignals.index', { status: ready ? t('projectsPage.surfaceSignals.ready') : t('projectsPage.surfaceSignals.missing') }),
      timeline: (ready: boolean) => t('projectsPage.surfaceSignals.timeline', { status: ready ? t('projectsPage.surfaceSignals.ready') : t('projectsPage.surfaceSignals.missing') }),
      recaps: (count: number) => t('projectsPage.surfaceSignals.recaps', { count }),
      knowledge: (count: number) => t('projectsPage.surfaceSignals.knowledge', { count }),
      citizens: (count: number) => t('projectsPage.surfaceSignals.citizens', { count }),
      pendingTodos: (count: number) => t('projectsPage.surfaceSignals.pendingTodos', { count }),
    },
    loadingTitle: t('projectsPage.loadingTitle'),
    emptyTitle: t('projectsPage.emptyTitle'),
    filteredEmptyTitle: t('projectsPage.filteredEmptyTitle'),
  };
}

export function useWorkspaceBootstrapPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('workspaceBootstrap.kicker'),
    title: t('workspaceBootstrap.title'),
    summary: t('workspaceBootstrap.summary'),
    runtimeReadyLabel: t('workspaceBootstrap.runtimeReadyLabel'),
    bootstrapTaskLabel: t('workspaceBootstrap.bootstrapTaskLabel'),
    completedLabel: t('workspaceBootstrap.completedLabel'),
    readyValue: t('workspaceBootstrap.readyValue'),
    blockedValue: t('workspaceBootstrap.blockedValue'),
    completedValue: t('workspaceBootstrap.completedValue'),
    pendingValue: t('workspaceBootstrap.pendingValue'),
    guideTitle: t('workspaceBootstrap.guideTitle'),
    guideSummary: t('workspaceBootstrap.guideSummary'),
    guideSteps: t('workspaceBootstrap.guideSteps', { returnObjects: true }) as string[],
    runtimeReasonLabel: t('workspaceBootstrap.runtimeReasonLabel'),
    emptyTaskValue: t('workspaceBootstrap.emptyTaskValue'),
    openTaskAction: t('workspaceBootstrap.openTaskAction'),
  };
}

export function useProjectDetailPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('projectDetail.kicker'),
    loadingTitle: t('projectDetail.loadingTitle'),
    notFoundTitle: t('projectDetail.notFoundTitle'),
    emptySummary: t('projectDetail.emptySummary'),
    openBrainAction: t('projectDetail.openBrainAction'),
    openKnowledgeAction: t('projectDetail.openKnowledgeAction'),
    openArchiveAction: t('projectDetail.openArchiveAction'),
    openOperatorAction: t('projectDetail.openOperatorAction'),
    overviewTitle: t('projectDetail.overviewTitle'),
    surfacesTitle: t('projectDetail.surfacesTitle'),
    workTitle: t('projectDetail.workTitle'),
    operatorTitle: t('projectDetail.operatorTitle'),
    operatorSummary: t('projectDetail.operatorSummary'),
    showOperatorAction: t('projectDetail.showOperatorAction'),
    hideOperatorAction: t('projectDetail.hideOperatorAction'),
    operatorSafeActionsTitle: t('projectDetail.operatorSafeActionsTitle'),
    operatorAdvancedActionsTitle: t('projectDetail.operatorAdvancedActionsTitle'),
    operatorReportsTitle: t('projectDetail.operatorReportsTitle'),
    surfacePathLabel: t('projectDetail.surfacePathLabel'),
    surfaceUpdatedLabel: t('projectDetail.surfaceUpdatedLabel'),
    surfaceSourceTasksLabel: t('projectDetail.surfaceSourceTasksLabel'),
    emptySurface: t('projectDetail.emptySurface'),
    ownerLabel: t('projectDetail.ownerLabel'),
    membersTitle: t('projectDetail.membersTitle'),
    membersEmpty: t('projectDetail.membersEmpty'),
    statusLabel: t('projectDetail.statusLabel'),
    updatedLabel: t('projectDetail.updatedLabel'),
    repoBoundLabel: t('projectDetail.repoBoundLabel'),
    citizenCountLabel: t('projectDetail.citizenCountLabel'),
    nomosTitle: t('projectDetail.nomosTitle'),
    nomosIdLabel: t('projectDetail.nomosIdLabel'),
    projectStateRootLabel: t('projectDetail.projectStateRootLabel'),
    bootstrapPromptsLabel: t('projectDetail.bootstrapPromptsLabel'),
    repoPathLabel: t('projectDetail.repoPathLabel'),
    repoShimInstalledLabel: t('projectDetail.repoShimInstalledLabel'),
    profileInstalledLabel: t('projectDetail.profileInstalledLabel'),
    lifecycleModulesLabel: t('projectDetail.lifecycleModulesLabel'),
    activationStatusLabel: t('projectDetail.activationStatusLabel'),
    draftRootLabel: t('projectDetail.draftRootLabel'),
    activeRootLabel: t('projectDetail.activeRootLabel'),
    reinstallNomosAction: t('projectDetail.reinstallNomosAction'),
    rerunBootstrapAction: t('projectDetail.rerunBootstrapAction'),
    runDoctorAction: t('projectDetail.runDoctorAction'),
    reviewNomosAction: t('projectDetail.reviewNomosAction'),
    activateNomosAction: t('projectDetail.activateNomosAction'),
    validateNomosAction: t('projectDetail.validateNomosAction'),
    diffNomosAction: t('projectDetail.diffNomosAction'),
    exportNomosAction: t('projectDetail.exportNomosAction'),
    publishNomosAction: t('projectDetail.publishNomosAction'),
    installPackAction: t('projectDetail.installPackAction'),
    refreshCatalogAction: t('projectDetail.refreshCatalogAction'),
    showCatalogEntryAction: t('projectDetail.showCatalogEntryAction'),
    installCatalogPackAction: t('projectDetail.installCatalogPackAction'),
    nomosActionPending: t('projectDetail.nomosActionPending'),
    nomosReinstallSuccess: t('projectDetail.nomosReinstallSuccess'),
    nomosBootstrapSuccess: t('projectDetail.nomosBootstrapSuccess'),
    nomosDoctorSuccess: t('projectDetail.nomosDoctorSuccess'),
    nomosReviewSuccess: t('projectDetail.nomosReviewSuccess'),
    nomosActivateSuccess: t('projectDetail.nomosActivateSuccess'),
    nomosValidateSuccess: t('projectDetail.nomosValidateSuccess'),
    nomosDiffSuccess: t('projectDetail.nomosDiffSuccess'),
    nomosExportSuccess: t('projectDetail.nomosExportSuccess'),
    nomosInstallPackSuccess: t('projectDetail.nomosInstallPackSuccess'),
    nomosPublishSuccess: t('projectDetail.nomosPublishSuccess'),
    nomosInstallCatalogSuccess: t('projectDetail.nomosInstallCatalogSuccess'),
    nomosImportSourceSuccess: t('projectDetail.nomosImportSourceSuccess'),
    nomosInstallSourceSuccess: t('projectDetail.nomosInstallSourceSuccess'),
    nomosRegisterSourceSuccess: t('projectDetail.nomosRegisterSourceSuccess'),
    nomosSyncSourceSuccess: t('projectDetail.nomosSyncSourceSuccess'),
    nomosInstallRegisteredSourceSuccess: t('projectDetail.nomosInstallRegisteredSourceSuccess'),
    exportDirLabel: t('projectDetail.exportDirLabel'),
    exportDirPlaceholder: t('projectDetail.exportDirPlaceholder'),
    packDirLabel: t('projectDetail.packDirLabel'),
    packDirPlaceholder: t('projectDetail.packDirPlaceholder'),
    sourceDirLabel: t('projectDetail.sourceDirLabel'),
    sourceIdLabel: t('projectDetail.sourceIdLabel'),
    sourceDirPlaceholder: t('projectDetail.sourceDirPlaceholder'),
    sourceIdPlaceholder: t('projectDetail.sourceIdPlaceholder'),
    publishNoteLabel: t('projectDetail.publishNoteLabel'),
    publishNotePlaceholder: t('projectDetail.publishNotePlaceholder'),
    catalogPackIdLabel: t('projectDetail.catalogPackIdLabel'),
    catalogPackIdPlaceholder: t('projectDetail.catalogPackIdPlaceholder'),
    sourceKindLabel: t('projectDetail.sourceKindLabel'),
    catalogTitle: t('projectDetail.catalogTitle'),
    catalogRootLabel: t('projectDetail.catalogRootLabel'),
    catalogSelectionTitle: t('projectDetail.catalogSelectionTitle'),
    catalogEmpty: t('projectDetail.catalogEmpty'),
    importSourceAction: t('projectDetail.importSourceAction'),
    installFromSourceAction: t('projectDetail.installFromSourceAction'),
    registerSourceAction: t('projectDetail.registerSourceAction'),
    refreshSourcesAction: t('projectDetail.refreshSourcesAction'),
    showSourceEntryAction: t('projectDetail.showSourceEntryAction'),
    syncRegisteredSourceAction: t('projectDetail.syncRegisteredSourceAction'),
    installRegisteredSourceAction: t('projectDetail.installRegisteredSourceAction'),
    importedSourceTitle: t('projectDetail.importedSourceTitle'),
    registeredSourcesTitle: t('projectDetail.registeredSourcesTitle'),
    registeredSourcesRootLabel: t('projectDetail.registeredSourcesRootLabel'),
    registeredSourcesEmpty: t('projectDetail.registeredSourcesEmpty'),
    registeredSourceSelectionTitle: t('projectDetail.registeredSourceSelectionTitle'),
    doctorTitle: t('projectDetail.doctorTitle'),
    doctorEmbeddingLabel: t('projectDetail.doctorEmbeddingLabel'),
    doctorVectorLabel: t('projectDetail.doctorVectorLabel'),
    doctorJobsLabel: t('projectDetail.doctorJobsLabel'),
    doctorDriftLabel: t('projectDetail.doctorDriftLabel'),
    reviewTitle: t('projectDetail.reviewTitle'),
    reviewCanActivateLabel: t('projectDetail.reviewCanActivateLabel'),
    reviewIssuesLabel: t('projectDetail.reviewIssuesLabel'),
    reviewActivePackLabel: t('projectDetail.reviewActivePackLabel'),
    reviewDraftPackLabel: t('projectDetail.reviewDraftPackLabel'),
    validationTitle: t('projectDetail.validationTitle'),
    validationTargetLabel: t('projectDetail.validationTargetLabel'),
    validationValidLabel: t('projectDetail.validationValidLabel'),
    validationIssuesLabel: t('projectDetail.validationIssuesLabel'),
    diffTitle: t('projectDetail.diffTitle'),
    diffChangedLabel: t('projectDetail.diffChangedLabel'),
    diffBaseLabel: t('projectDetail.diffBaseLabel'),
    diffCandidateLabel: t('projectDetail.diffCandidateLabel'),
    diffFieldsLabel: t('projectDetail.diffFieldsLabel'),
    noneLabel: t('projectDetail.noneLabel'),
    yesLabel: t('projectDetail.yesLabel'),
    noLabel: t('projectDetail.noLabel'),
    stats: {
      knowledge: t('projectDetail.stats.knowledge'),
      citizens: t('projectDetail.stats.citizens'),
      recaps: t('projectDetail.stats.recaps'),
      activeTasks: t('projectDetail.stats.activeTasks'),
      waitingReview: t('projectDetail.stats.waitingReview'),
      pendingTodos: t('projectDetail.stats.pendingTodos'),
    },
    recapsTitle: t('projectDetail.recapsTitle'),
    recapsEmpty: t('projectDetail.recapsEmpty'),
    openRecapAria: (title: string) => t('projectDetail.openRecapAria', { title }),
    knowledgeTitle: t('projectDetail.knowledgeTitle'),
    knowledgeEmpty: t('projectDetail.knowledgeEmpty'),
    openKnowledgeAria: (title: string) => t('projectDetail.openKnowledgeAria', { title }),
    relatedTasksTitle: t('projectDetail.relatedTasksTitle'),
    taskFilters: {
      all: t('projectDetail.taskFilters.all'),
      active: t('projectDetail.taskFilters.active'),
      review: t('projectDetail.taskFilters.review'),
    },
    relatedTasksEmpty: t('projectDetail.relatedTasksEmpty'),
    citizensTitle: t('projectDetail.citizensTitle'),
    createTaskAction: t('projectDetail.createTaskAction'),
    createTodoAction: t('projectDetail.createTodoAction'),
    workspaceHandoffsTitle: t('projectDetail.workspaceHandoffsTitle'),
    workspaceHandoffsKnowledgeSummary: (count: number) => t('projectDetail.workspaceHandoffsKnowledgeSummary', { count }),
    workspaceHandoffsArchiveSummary: (count: number) => t('projectDetail.workspaceHandoffsArchiveSummary', { count }),
    workspaceHandoffsOperatorSummary: (count: number) => t('projectDetail.workspaceHandoffsOperatorSummary', { count }),
    citizensEmpty: t('projectDetail.citizensEmpty'),
    citizenPreviewLabel: t('projectDetail.citizenPreviewLabel'),
    openCitizenAria: (name: string) => t('projectDetail.openCitizenAria', { name }),
    relatedTodosTitle: t('projectDetail.relatedTodosTitle'),
    todoFilters: {
      all: t('projectDetail.todoFilters.all'),
      pending: t('projectDetail.todoFilters.pending'),
    },
    taskStateLabels: {
      in_progress: t('projectDetail.taskStateLabels.in_progress'),
      gate_waiting: t('projectDetail.taskStateLabels.gate_waiting'),
      active: t('projectDetail.taskStateLabels.active'),
      paused: t('projectDetail.taskStateLabels.paused'),
      blocked: t('projectDetail.taskStateLabels.blocked'),
      pending: t('projectDetail.taskStateLabels.pending'),
      done: t('projectDetail.taskStateLabels.done'),
    },
    todoStatusLabels: {
      pending: t('projectDetail.todoStatusLabels.pending'),
      done: t('projectDetail.todoStatusLabels.done'),
    },
    knowledgeKindLabels: {
      decision: t('projectDetail.knowledgeKindLabels.decision'),
      fact: t('projectDetail.knowledgeKindLabels.fact'),
      open_question: t('projectDetail.knowledgeKindLabels.open_question'),
      reference: t('projectDetail.knowledgeKindLabels.reference'),
    },
    relatedTodosEmpty: t('projectDetail.relatedTodosEmpty'),
    reopenTodoAction: t('projectDetail.reopenTodoAction'),
    markTodoDoneAction: t('projectDetail.markTodoDoneAction'),
    promoteTodoAction: t('projectDetail.promoteTodoAction'),
    deleteTodoAction: t('projectDetail.deleteTodoAction'),
    recapDialogLabel: t('projectDetail.recapDialogLabel'),
    recapContentTitle: t('projectDetail.recapContentTitle'),
    documentFallback: t('projectDetail.documentFallback'),
    knowledgeDialogLabel: t('projectDetail.knowledgeDialogLabel'),
    knowledgeSourceTasksTitle: t('projectDetail.knowledgeSourceTasksTitle'),
    noSourceTasks: t('projectDetail.noSourceTasks'),
    knowledgeContentTitle: t('projectDetail.knowledgeContentTitle'),
    citizenDialogLabel: t('projectDetail.citizenDialogLabel'),
    personaTitle: t('projectDetail.personaTitle'),
    noPersona: t('projectDetail.noPersona'),
    boundariesTitle: t('projectDetail.boundariesTitle'),
    noBoundaries: t('projectDetail.noBoundaries'),
    skillsTitle: t('projectDetail.skillsTitle'),
    noSkills: t('projectDetail.noSkills'),
    channelPoliciesTitle: t('projectDetail.channelPoliciesTitle'),
    runtimeMetadataTitle: t('projectDetail.runtimeMetadataTitle'),
  };
}

export function useProjectBrainPageCopy() {
  const { t } = useTranslation();

  return {
    loadingTitle: t('projectBrain.loadingTitle'),
    notFoundTitle: t('projectBrain.notFoundTitle'),
    kicker: t('projectBrain.kicker'),
    title: t('projectBrain.title'),
    surfaceTitle: t('projectBrain.surfaceTitle'),
    filters: {
      all: t('projectBrain.filters.all'),
      core: t('projectBrain.filters.core'),
      knowledge: t('projectBrain.filters.knowledge'),
      recaps: t('projectBrain.filters.recaps'),
      citizens: t('projectBrain.filters.citizens'),
    },
    searchLabel: t('projectBrain.searchLabel'),
    searchPlaceholder: t('projectBrain.searchPlaceholder'),
    openBrainItemAria: (label: string) => t('projectBrain.openBrainItemAria', { label }),
    emptyListTitle: t('projectBrain.emptyListTitle'),
    detailEmptyTitle: t('projectBrain.detailEmptyTitle'),
    detailEmptySummary: t('projectBrain.detailEmptySummary'),
    indexFallbackTitle: t('projectBrain.indexFallbackTitle'),
    timelineFallbackTitle: t('projectBrain.timelineFallbackTitle'),
    sourceTasksTitle: t('projectBrain.sourceTasksTitle'),
    noSourceTasks: t('projectBrain.noSourceTasks'),
    openSourceTaskAction: (taskId: string) => t('projectBrain.openSourceTaskAction', { taskId }),
    citizenIdentityTitle: t('projectBrain.citizenIdentityTitle'),
    personaTitle: t('projectBrain.personaTitle'),
    noPersona: t('projectBrain.noPersona'),
    boundariesTitle: t('projectBrain.boundariesTitle'),
    noBoundaries: t('projectBrain.noBoundaries'),
    skillsTitle: t('projectBrain.skillsTitle'),
    noSkills: t('projectBrain.noSkills'),
    channelPoliciesTitle: t('projectBrain.channelPoliciesTitle'),
    runtimeMetadataTitle: t('projectBrain.runtimeMetadataTitle'),
    contentTitle: t('projectBrain.contentTitle'),
    actionBridgeTitle: t('projectBrain.actionBridgeTitle'),
    backToProjectDetailAction: t('projectBrain.backToProjectDetailAction'),
    createTaskInProjectAction: t('projectBrain.createTaskInProjectAction'),
    createTodoInProjectAction: t('projectBrain.createTodoInProjectAction'),
    kindLabels: {
      core: t('projectBrain.kindLabels.core'),
      recap: t('projectBrain.kindLabels.recap'),
      knowledge: t('projectBrain.kindLabels.knowledge'),
      citizen: t('projectBrain.kindLabels.citizen'),
    },
  };
}

export function useTasksPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('tasks.kicker'),
    title: t('tasks.title'),
    summary: t('tasks.summary'),
    workbenchTitle: t('tasks.workbenchTitle'),
    workbenchSummary: t('tasks.workbenchSummary'),
    filterAction: t('tasks.filterAction'),
    clearFiltersAction: t('tasks.clearFiltersAction'),
    applyFiltersAction: t('tasks.applyFiltersAction'),
    detailAction: t('tasks.detailAction'),
    detailDialogLabel: t('tasks.detailDialogLabel'),
    detailDialogTitle: t('tasks.detailDialogTitle'),
    detailLoadingTitle: t('tasks.detailLoadingTitle'),
    detailLoadingSummary: t('tasks.detailLoadingSummary'),
    detailErrorTitle: t('tasks.detailErrorTitle'),
    detailEmptyTitle: t('tasks.detailEmptyTitle'),
    detailEmptySummary: t('tasks.detailEmptySummary'),
    quickViewTitle: t('tasks.quickViewTitle'),
    filterSectionLabels: {
      state: t('tasks.filterSectionLabels.state'),
      priority: t('tasks.filterSectionLabels.priority'),
      project: t('tasks.filterSectionLabels.project'),
      team: t('tasks.filterSectionLabels.team'),
      workflow: t('tasks.filterSectionLabels.workflow'),
    },
    projectLabel: t('tasks.projectLabel'),
    unassignedProjectLabel: t('tasks.unassignedProjectLabel'),
    filterEmpty: t('tasks.filterEmpty'),
    activeFilterPrefix: t('tasks.activeFilterPrefix'),
    searchPlaceholder: t('tasks.searchPlaceholder'),
    listKicker: t('tasks.listKicker'),
    listTitle: t('tasks.listTitle'),
    listCountUnit: t('tasks.listCountUnit'),
    detailKicker: t('tasks.detailKicker'),
    stageLabel: t('tasks.stageLabel'),
    stageFallback: t('tasks.stageFallback'),
    workflowLabel: t('tasks.workflowLabel'),
    teamLabel: t('tasks.teamLabel'),
    controllerLabel: t('tasks.controllerLabel'),
    updatedLabel: t('tasks.updatedLabel'),
    briefFallback: t('tasks.briefFallback'),
    timelineTitle: t('tasks.timelineTitle'),
    timelineEmptyDetail: t('tasks.timelineEmptyDetail'),
    blueprintTitle: t('tasks.blueprintTitle'),
    blueprintEmpty: t('tasks.blueprintEmpty'),
    blueprintEntryLabel: t('tasks.blueprintEntryLabel'),
    blueprintControllerLabel: t('tasks.blueprintControllerLabel'),
    blueprintNodesLabel: t('tasks.blueprintNodesLabel'),
    blueprintEdgesLabel: t('tasks.blueprintEdgesLabel'),
    blueprintArtifactsLabel: t('tasks.blueprintArtifactsLabel'),
    stageRosterTitle: t('tasks.stageRosterTitle'),
    stageRosterDesiredLabel: t('tasks.stageRosterDesiredLabel'),
    stageRosterJoinedLabel: t('tasks.stageRosterJoinedLabel'),
    stageRosterRulesLabel: t('tasks.stageRosterRulesLabel'),
    stageRosterRulesKeepController: t('tasks.stageRosterRulesKeepController'),
    stageRosterRulesNone: t('tasks.stageRosterRulesNone'),
    conversationTitle: t('tasks.conversationTitle'),
    conversationEmpty: t('tasks.conversationEmpty'),
    progressTitle: t('tasks.progressTitle'),
    subtasksTitle: t('tasks.subtasksTitle'),
    subtaskFallbackType: t('tasks.subtaskFallbackType'),
    subtaskCloseAction: t('tasks.subtaskCloseAction'),
    subtaskArchiveAction: t('tasks.subtaskArchiveAction'),
    subtaskCancelAction: t('tasks.subtaskCancelAction'),
    executionTitle: t('tasks.executionTitle'),
    executionListLabel: t('tasks.executionListLabel'),
    executionEmpty: t('tasks.executionEmpty'),
    executionObserveAction: t('tasks.executionObserveAction'),
    executionObserveSuccess: t('tasks.executionObserveSuccess'),
    executionProbeAction: t('tasks.executionProbeAction'),
    executionProbeSuccess: t('tasks.executionProbeSuccess'),
    executionTailLabel: t('tasks.executionTailLabel'),
    executionTailEmpty: t('tasks.executionTailEmpty'),
    executionTailUnavailable: t('tasks.executionTailUnavailable'),
    executionTailAction: t('tasks.executionTailAction'),
    executionTailRefreshAction: t('tasks.executionTailRefreshAction'),
    executionTailLiveLabel: t('tasks.executionTailLiveLabel'),
    executionTailSnapshotLabel: t('tasks.executionTailSnapshotLabel'),
    executionTailUpdatedLabel: t('tasks.executionTailUpdatedLabel'),
    executionTailPollingLabel: t('tasks.executionTailPollingLabel'),
    executionTextLabel: t('tasks.executionTextLabel'),
    executionTextPlaceholder: t('tasks.executionTextPlaceholder'),
    executionTextAction: t('tasks.executionTextAction'),
    executionInputSuccess: t('tasks.executionInputSuccess'),
    executionStopAction: t('tasks.executionStopAction'),
    executionChoiceLabel: t('tasks.executionChoiceLabel'),
    executionKeysLabel: t('tasks.executionKeysLabel'),
    executionCountUnit: t('tasks.executionCountUnit'),
    governanceTitle: t('tasks.governanceTitle'),
    governanceActiveLabel: t('tasks.governanceActiveLabel'),
    governancePerAgentLabel: t('tasks.governancePerAgentLabel'),
    governanceMemoryLabel: t('tasks.governanceMemoryLabel'),
    governanceLoadLabel: t('tasks.governanceLoadLabel'),
    governancePressureLabel: t('tasks.governancePressureLabel'),
    governanceWarningsLabel: t('tasks.governanceWarningsLabel'),
    governanceExecutionDetailsLabel: t('tasks.governanceExecutionDetailsLabel'),
    governanceAssigneeLabel: t('tasks.governanceAssigneeLabel'),
    runtimeRecoveryTitle: t('tasks.runtimeRecoveryTitle'),
    runtimeDiagnosisAction: t('tasks.runtimeDiagnosisAction'),
    runtimeRestartAction: t('tasks.runtimeRestartAction'),
    actionsTitle: t('tasks.actionsTitle'),
    actorLabel: t('tasks.actorLabel'),
    noteLabel: t('tasks.noteLabel'),
    notePlaceholder: t('tasks.notePlaceholder'),
    advanceAction: t('tasks.advanceAction'),
    approveAction: t('tasks.approveAction'),
    rejectAction: t('tasks.rejectAction'),
    confirmApproveAction: t('tasks.confirmApproveAction'),
    confirmRejectAction: t('tasks.confirmRejectAction'),
    pauseAction: t('tasks.pauseAction'),
    resumeAction: t('tasks.resumeAction'),
    cancelAction: t('tasks.cancelAction'),
    unblockAction: t('tasks.unblockAction'),
    forceAdvanceAction: t('tasks.forceAdvanceAction'),
    emptyTitle: t('tasks.emptyTitle'),
    emptySummary: t('tasks.emptySummary'),
    stats: {
      currentMatches: t('tasks.stats.currentMatches'),
      awaitingReview: t('tasks.stats.awaitingReview'),
      currentFocus: t('tasks.stats.currentFocus'),
    },
  };
}

export function useReviewsPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('reviews.kicker'),
    title: t('reviews.title'),
    summary: t('reviews.summary'),
    workbenchTitle: t('reviews.workbenchTitle'),
    workbenchSummary: t('reviews.workbenchSummary'),
    filterAction: t('reviews.filterAction'),
    clearFiltersAction: t('reviews.clearFiltersAction'),
    applyFiltersAction: t('reviews.applyFiltersAction'),
    detailAction: t('reviews.detailAction'),
    detailDialogLabel: t('reviews.detailDialogLabel'),
    detailDialogTitle: t('reviews.detailDialogTitle'),
    filterSectionLabels: {
      priority: t('reviews.filterSectionLabels.priority'),
      gate: t('reviews.filterSectionLabels.gate'),
      creator: t('reviews.filterSectionLabels.creator'),
    },
    activeFilterPrefix: t('reviews.activeFilterPrefix'),
    metricLabels: {
      queue: t('reviews.metricLabels.queue'),
      highestRisk: t('reviews.metricLabels.highestRisk'),
      defaultAction: t('reviews.metricLabels.defaultAction'),
    },
    metricValues: {
      highestRisk: t('reviews.metricValues.highestRisk'),
      normal: t('reviews.metricValues.normal'),
      defaultAction: t('reviews.metricValues.defaultAction'),
    },
    queueKicker: t('reviews.queueKicker'),
    queueTitle: t('reviews.queueTitle'),
    queueCountUnit: t('reviews.queueCountUnit'),
    queueFallbackSummary: t('reviews.queueFallbackSummary'),
    queueFallbackImpactPrefix: t('reviews.queueFallbackImpactPrefix'),
    queueFallbackImpactSuffix: t('reviews.queueFallbackImpactSuffix'),
    workspaceKicker: t('reviews.workspaceKicker'),
    workspaceTitle: t('reviews.workspaceTitle'),
    gateLabel: t('reviews.gateLabel'),
    impactLabel: t('reviews.impactLabel'),
    contextTitle: t('reviews.contextTitle'),
    progressTitle: t('reviews.progressTitle'),
    noteLabel: t('reviews.noteLabel'),
    notePlaceholder: t('reviews.notePlaceholder'),
    rejectAction: t('reviews.rejectAction'),
    approveAction: t('reviews.approveAction'),
    emptyTitle: t('reviews.emptyTitle'),
    emptySummary: t('reviews.emptySummary'),
    queueScopes: {
      assigned: t('reviews.queueScopes.assigned'),
      high: t('reviews.queueScopes.high'),
    },
    tableHeaders: {
      task: t('reviews.tableHeaders.task'),
      gate: t('reviews.tableHeaders.gate'),
      priority: t('reviews.tableHeaders.priority'),
      wait: t('reviews.tableHeaders.wait'),
    },
    liveApiNotice: t('reviews.liveApiNotice'),
    readOnlyNotice: t('reviews.readOnlyNotice'),
  };
}

export function useAgentsPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('agents.kicker'),
    title: t('agents.title'),
    summary: t('agents.summary'),
    metrics: {
      activeTasks: t('agents.metrics.activeTasks'),
      activeAgents: t('agents.metrics.activeAgents'),
      totalAgents: t('agents.metrics.totalAgents'),
      onlineAgents: t('agents.metrics.onlineAgents'),
      staleAgents: t('agents.metrics.staleAgents'),
      disconnectedAgents: t('agents.metrics.disconnectedAgents'),
      busyCraftsmen: t('agents.metrics.busyCraftsmen'),
    },
    channelSummaryTitle: t('agents.channelSummaryTitle'),
    hostSummaryTitle: t('agents.hostSummaryTitle'),
    channelDetailTitle: t('agents.channelDetailTitle'),
    channelTimelineTitle: t('agents.channelTimelineTitle'),
    channelSignalsTitle: t('agents.channelSignalsTitle'),
    runtimeSummaryTitle: t('agents.runtimeSummaryTitle'),
    runtimeTitle: t('agents.tmuxRuntimeTitle'),
    filtersTitle: t('agents.filtersTitle'),
    filterLabels: {
      all: t('agents.filterLabels.all'),
      busy: t('agents.filterLabels.busy'),
      online: t('agents.filterLabels.online'),
      stale: t('agents.filterLabels.stale'),
      disconnected: t('agents.filterLabels.disconnected'),
      offline: t('agents.filterLabels.offline'),
    },
    selectabilityFilterLabel: t('agents.selectabilityFilterLabel'),
    selectabilityFilterLabels: {
      all: t('agents.selectabilityFilterLabels.all'),
      selectable: t('agents.selectabilityFilterLabels.selectable'),
      restricted: t('agents.selectabilityFilterLabels.restricted'),
    },
    agentListTitle: t('agents.agentListTitle'),
    craftsmenTitle: t('agents.craftsmenTitle'),
    emptyAgents: t('agents.emptyAgents'),
    emptyCraftsmen: t('agents.emptyCraftsmen'),
    roleLabel: t('agents.roleLabel'),
    channelLabel: t('agents.channelLabel'),
    hostLabel: t('agents.hostLabel'),
    inventorySourcesLabel: t('agents.inventorySourcesLabel'),
    modelLabel: t('agents.modelLabel'),
    presenceLabel: t('agents.presenceLabel'),
    presenceReasonLabel: t('agents.presenceReasonLabel'),
    selectabilityLabel: t('agents.selectabilityLabel'),
    selectabilityReasonLabel: t('agents.selectabilityReasonLabel'),
    selectabilityReasonLabels: {
      active_assignment: t('selectabilityReasons.active_assignment'),
      inventory_launchable: t('selectabilityReasons.inventory_launchable'),
      stale_observation: t('selectabilityReasons.stale_observation'),
      provider_disconnected: t('selectabilityReasons.provider_disconnected'),
      unbound_agent: t('selectabilityReasons.unbound_agent'),
      legacy_presence_gate: t('selectabilityReasons.legacy_presence_gate'),
      legacy_presence_ok: t('selectabilityReasons.legacy_presence_ok'),
      unknown: t('selectabilityReasons.unknown'),
    } satisfies AgentSelectabilityReasonLabels,
    accountLabel: t('agents.accountLabel'),
    statusLabel: t('agents.statusLabel'),
    lastSeenLabel: t('agents.lastSeenLabel'),
    loadLabel: t('agents.loadLabel'),
    taskCountLabel: t('agents.taskCountLabel'),
    subtaskCountLabel: t('agents.subtaskCountLabel'),
    currentTaskLabel: t('agents.currentTaskLabel'),
    runtimeSessionLabel: t('agents.runtimeSessionLabel'),
    runtimePanesLabel: t('agents.runtimePanesLabel'),
    runtimeReadyPanesLabel: t('agents.runtimeReadyPanesLabel'),
    runtimeActivePanesLabel: t('agents.runtimeActivePanesLabel'),
    runtimeRunningCraftsmenLabel: t('agents.runtimeRunningCraftsmenLabel'),
    runtimeFailedCraftsmenLabel: t('agents.runtimeFailedCraftsmenLabel'),
    readyLabel: t('agents.readyLabel'),
    paneLabel: t('agents.paneLabel'),
    commandLabel: t('agents.commandLabel'),
    tailPreviewLabel: t('agents.tailPreviewLabel'),
    loadTailAction: t('agents.loadTailAction'),
    loadingTailAction: t('agents.loadingTailAction'),
    continuityBackendLabel: t('agents.continuityBackendLabel'),
    resumeCapabilityLabel: t('agents.resumeCapabilityLabel'),
    sessionReferenceLabel: t('agents.sessionReferenceLabel'),
    identitySourceLabel: t('agents.identitySourceLabel'),
    identityPathLabel: t('agents.identityPathLabel'),
    observedAtLabel: t('agents.observedAtLabel'),
    recoveryModeLabel: t('agents.recoveryModeLabel'),
    emptyChannelDetail: t('agents.emptyChannelDetail'),
    emptyChannelHistory: t('agents.emptyChannelHistory'),
    emptyChannelSignals: t('agents.emptyChannelSignals'),
    emptyHostSummary: t('agents.emptyHostSummary'),
    emptyRuntime: t('agents.emptyTmuxRuntime'),
    workspace: {
      overviewKicker: t('agents.workspace.overviewKicker'),
      overviewTitle: t('agents.workspace.overviewTitle'),
      focusKicker: t('agents.workspace.focusKicker'),
      focusTitle: t('agents.workspace.focusTitle'),
      issueQueueKicker: t('agents.workspace.issueQueueKicker'),
      issueQueueTitle: t('agents.workspace.issueQueueTitle'),
      detailEntryKicker: t('agents.workspace.detailEntryKicker'),
      detailEntryTitle: t('agents.workspace.detailEntryTitle'),
      attentionLabel: t('agents.workspace.attentionLabel'),
      stableLabel: t('agents.workspace.stableLabel'),
      issueCountOpen: (count: number) => t('agents.workspace.issueCountOpen', { count }),
      issueCountStable: t('agents.workspace.issueCountStable'),
      channelFocusLabel: t('agents.workspace.channelFocusLabel'),
      channelFocusMessage: (channel: string) => t('agents.workspace.channelFocusMessage', { channel }),
      channelFocusEmpty: t('agents.workspace.channelFocusEmpty'),
      agentFocusLabel: t('agents.workspace.agentFocusLabel'),
      agentCriticalMessage: (agent: string) => t('agents.workspace.agentCriticalMessage', { agent }),
      agentStaleMessage: (agent: string) => t('agents.workspace.agentStaleMessage', { agent }),
      agentFocusEmpty: t('agents.workspace.agentFocusEmpty'),
      executionFocusLabel: t('agents.workspace.executionFocusLabel'),
      executionFailedMessage: (count: number) => t('agents.workspace.executionFailedMessage', { count }),
      executionReadyMessage: (ready: number, total: number) => t('agents.workspace.executionReadyMessage', { ready, total }),
      issueQueueEmpty: t('agents.workspace.issueQueueEmpty'),
      issueGroups: {
        channelHealth: t('agents.workspace.issueGroups.channelHealth'),
        agentCritical: t('agents.workspace.issueGroups.agentCritical'),
        agentStale: t('agents.workspace.issueGroups.agentStale'),
        craftsmanFailed: t('agents.workspace.issueGroups.craftsmanFailed'),
        runtimeUnhealthy: t('agents.workspace.issueGroups.tmuxUnhealthy'),
        channelSummary: (count: number) => t('agents.workspace.issueGroups.channelSummary', { count }),
        channelDetail: (channel: string, presence: string, transportErrors: number) =>
          t('agents.workspace.issueGroups.channelDetail', { channel, presence, transportErrors }),
        agentCriticalSummary: (count: number) => t('agents.workspace.issueGroups.agentCriticalSummary', { count }),
        agentCriticalDetail: (agent: string) => t('agents.workspace.issueGroups.agentCriticalDetail', { agent }),
        agentStaleSummary: (count: number) => t('agents.workspace.issueGroups.agentStaleSummary', { count }),
        agentStaleDetail: (agent: string) => t('agents.workspace.issueGroups.agentStaleDetail', { agent }),
        craftsmanFailedSummary: (count: number) => t('agents.workspace.issueGroups.craftsmanFailedSummary', { count }),
        craftsmanFailedDetail: (craftsman: string) => t('agents.workspace.issueGroups.craftsmanFailedDetail', { craftsman }),
        runtimeUnhealthySummary: (count: number) => t('agents.workspace.issueGroups.tmuxUnhealthySummary', { count }),
        runtimeUnhealthyDetail: (agent: string) => t('agents.workspace.issueGroups.tmuxUnhealthyDetail', { agent }),
      },
      signalNotes: {
        channels: (count: number) => t('agents.workspace.signalNotes.channels', { count }),
        craftsmen: (count: number) => t('agents.workspace.signalNotes.craftsmen', { count }),
        onlineAgents: (count: number) => t('agents.workspace.signalNotes.onlineAgents', { count }),
        readyPanes: (ready: number, total: number) => t('agents.workspace.signalNotes.readyPanes', { ready, total }),
      },
      signalLabels: {
        channelIssues: t('agents.workspace.signalLabels.channelIssues'),
        craftsmanFailures: t('agents.workspace.signalLabels.craftsmanFailures'),
        agentIssues: t('agents.workspace.signalLabels.agentIssues'),
        runtimeUnready: t('agents.workspace.signalLabels.tmuxUnready'),
      },
      axis: {
        agentAction: t('agents.workspace.axis.agentAction'),
        agentSummary: t('agents.workspace.axis.agentSummary'),
        channelAction: t('agents.workspace.axis.channelAction'),
        channelSummary: t('agents.workspace.axis.channelSummary'),
        executionAction: t('agents.workspace.axis.executionAction'),
        executionSummary: t('agents.workspace.axis.executionSummary'),
      },
      drawers: {
        agentLabel: t('agents.workspace.drawers.agentLabel'),
        agentTitle: t('agents.workspace.drawers.agentTitle'),
        channelLabel: t('agents.workspace.drawers.channelLabel'),
        channelTitle: t('agents.workspace.drawers.channelTitle'),
        executionLabel: t('agents.workspace.drawers.executionLabel'),
        executionTitle: t('agents.workspace.drawers.executionTitle'),
      },
      tabs: {
        summary: t('agents.workspace.tabs.summary'),
        signals: t('agents.workspace.tabs.signals'),
        history: t('agents.workspace.tabs.history'),
      },
    },
  };
}

export function useTodosPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('todos.kicker'),
    title: t('todos.title'),
    summary: t('todos.summary'),
    inputLabel: t('todos.inputLabel'),
    inputPlaceholder: t('todos.inputPlaceholder'),
    projectLabel: t('todos.projectLabel'),
    noProjectOption: t('todos.noProjectOption'),
    dueLabel: t('todos.dueLabel'),
    tagsLabel: t('todos.tagsLabel'),
    tagsPlaceholder: t('todos.tagsPlaceholder'),
    createAction: t('todos.createAction'),
    filters: {
      all: t('todos.filters.all'),
      pending: t('todos.filters.pending'),
      done: t('todos.filters.done'),
    },
    projectFilterLabel: t('todos.projectFilterLabel'),
    allProjectsOption: t('todos.allProjectsOption'),
    emptyTitle: t('todos.emptyTitle'),
    promoteAction: t('todos.promoteAction'),
    deleteAction: t('todos.deleteAction'),
    doneAction: t('todos.doneAction'),
    reopenAction: t('todos.reopenAction'),
    promotedPrefix: t('todos.promotedPrefix'),
  };
}

export function useArchivePageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('archive.kicker'),
    title: t('archive.title'),
    summary: t('archive.summary'),
    filters: {
      all: t('archive.filters.all'),
      pending: t('archive.filters.pending'),
      failed: t('archive.filters.failed'),
      completed: t('archive.filters.completed'),
    },
    taskIdLabel: t('archive.taskIdLabel'),
    detailTitle: t('archive.detailTitle'),
    emptyTitle: t('archive.emptyTitle'),
    payloadTitle: t('archive.payloadTitle'),
    nextActionLabel: t('archive.nextActionLabel'),
    approveAction: t('archive.approveAction'),
    confirmAction: t('archive.confirmAction'),
    completeAction: t('archive.completeAction'),
    retryAction: t('archive.retryAction'),
    requestedAtLabel: t('archive.requestedAtLabel'),
    completedAtLabel: t('archive.completedAtLabel'),
    targetPathLabel: t('archive.targetPathLabel'),
  };
}

export function useTemplatesPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('templates.kicker'),
    title: t('templates.title'),
    summary: t('templates.summary'),
    listTitle: t('templates.listTitle'),
    detailTitle: t('templates.detailTitle'),
    governanceLabel: t('templates.governanceLabel'),
    teamLabel: t('templates.teamLabel'),
    createAction: t('templates.createAction'),
    createIdLabel: t('templates.createIdLabel'),
    createNameLabel: t('templates.createNameLabel'),
    createIdPlaceholder: t('templates.createIdPlaceholder'),
    createNamePlaceholder: t('templates.createNamePlaceholder'),
    createHint: t('templates.createHint'),
    addRoleAction: t('templates.addRoleAction'),
    deleteRoleAction: t('templates.deleteRoleAction'),
    teamRoleSelectLabel: t('templates.teamRoleSelectLabel'),
    descriptionLabel: t('templates.descriptionLabel'),
    memberKindLabel: t('templates.memberKindLabel'),
    modelPreferenceLabel: t('templates.modelPreferenceLabel'),
    suggestedAgentsLabel: t('templates.suggestedAgentsLabel'),
    duplicateIdLabel: t('templates.duplicateIdLabel'),
    saveAction: t('templates.saveAction'),
    savingAction: t('templates.savingAction'),
    duplicateAction: t('templates.duplicateAction'),
    validateAction: t('templates.validateAction'),
    validationPassed: t('templates.validationPassed'),
    compatibilityTitle: t('templates.compatibilityTitle'),
    missingSuggestedLabel: t('templates.missingSuggestedLabel'),
    unavailableSuggestedLabel: t('templates.unavailableSuggestedLabel'),
    compatibilitySaveBlocked: t('templates.compatibilitySaveBlocked'),
    controllerSaveBlocked: t('templates.controllerSaveBlocked'),
    missingControllerLabel: t('templates.missingControllerLabel'),
    duplicateControllersLabel: t('templates.duplicateControllersLabel'),
    stagesTitle: t('templates.stagesTitle'),
    addStageAction: t('templates.addStageAction'),
    deleteStageAction: t('templates.deleteStageAction'),
    moveStageUpAction: t('templates.moveStageUpAction'),
    moveStageDownAction: t('templates.moveStageDownAction'),
    stageModeLabel: t('templates.stageModeLabel'),
    stageGateLabel: t('templates.stageGateLabel'),
    stageRejectTargetLabel: t('templates.stageRejectTargetLabel'),
    stageNoRejectTargetLabel: t('templates.stageNoRejectTargetLabel'),
    stageApproverLabel: t('templates.stageApproverLabel'),
    stageRequiredLabel: t('templates.stageRequiredLabel'),
    stageTimeoutLabel: t('templates.stageTimeoutLabel'),
    graphTitle: t('templates.graphTitle'),
    graphNodesLabel: t('templates.graphNodesLabel'),
    graphEdgesLabel: t('templates.graphEdgesLabel'),
    graphOpenEditorAction: t('templates.graphOpenEditorAction'),
    graphEditorSummary: t('templates.graphEditorSummary'),
    graphBackAction: t('templates.graphBackAction'),
    graphSaveAction: t('templates.graphSaveAction'),
    graphSaveBlocked: t('templates.graphSaveBlocked'),
    graphLoadingTitle: t('templates.graphLoadingTitle'),
    graphUnavailableTitle: t('templates.graphUnavailableTitle'),
    graphToolsTitle: t('templates.graphToolsTitle'),
    graphToolsHint: t('templates.graphToolsHint'),
    graphAddNodeAction: t('templates.graphAddNodeAction'),
    graphTidyLayoutAction: t('templates.graphTidyLayoutAction'),
    graphInspectorTitle: t('templates.graphInspectorTitle'),
    graphInspectorEmpty: t('templates.graphInspectorEmpty'),
    graphEntryLabel: t('templates.graphEntryLabel'),
    graphEntryToggleLabel: t('templates.graphEntryToggleLabel'),
    graphNodeNameLabel: t('templates.graphNodeNameLabel'),
    graphExecutionKindLabel: t('templates.graphExecutionKindLabel'),
    graphGateTypeLabel: t('templates.graphGateTypeLabel'),
    graphRosterRolesLabel: t('templates.graphRosterRolesLabel'),
    graphRosterKeepControllerLabel: t('templates.graphRosterKeepControllerLabel'),
    graphNextStageLabel: t('templates.graphNextStageLabel'),
    graphNoNextStageLabel: t('templates.graphNoNextStageLabel'),
    graphRejectTargetLabel: t('templates.graphRejectTargetLabel'),
    graphNoRejectTargetLabel: t('templates.graphNoRejectTargetLabel'),
    graphAddAdvanceEdgeAction: t('templates.graphAddAdvanceEdgeAction'),
    graphAddRejectEdgeAction: t('templates.graphAddRejectEdgeAction'),
    graphDeleteNodeAction: t('templates.graphDeleteNodeAction'),
    graphDeleteEdgeAction: t('templates.graphDeleteEdgeAction'),
    graphEdgeKindLabel: t('templates.graphEdgeKindLabel'),
    graphEdgeKindOptions: {
      advance: t('templates.graphEdgeKindOptions.advance'),
      reject: t('templates.graphEdgeKindOptions.reject'),
    },
    graphExecutionKindOptions: {
      default: t('templates.graphExecutionKindOptions.default'),
      citizen_discuss: t('templates.graphExecutionKindOptions.citizenDiscuss'),
      citizen_execute: t('templates.graphExecutionKindOptions.citizenExecute'),
      human_approval: t('templates.graphExecutionKindOptions.humanApproval'),
      craftsman_dispatch: t('templates.graphExecutionKindOptions.craftsmanDispatch'),
    },
    graphGateTypeOptions: {
      none: t('templates.graphGateTypeOptions.none'),
      command: t('templates.graphGateTypeOptions.command'),
      approval: t('templates.graphGateTypeOptions.approval'),
      archon_review: t('templates.graphGateTypeOptions.archonReview'),
      quorum: t('templates.graphGateTypeOptions.quorum'),
      all_subtasks_done: t('templates.graphGateTypeOptions.allSubtasksDone'),
      auto_timeout: t('templates.graphGateTypeOptions.autoTimeout'),
    },
    graphNodeSummary: (executionKind: string, gateType: string) => t('templates.graphNodeSummary', { executionKind, gateType }),
    graphValidationErrors: {
      missingNode: t('templates.graphValidationErrors.missingNode'),
      missingEntry: t('templates.graphValidationErrors.missingEntry'),
      unknownEntry: (entryId: string) => t('templates.graphValidationErrors.unknownEntry', { entryId }),
      unknownEdgeSource: (nodeId: string) => t('templates.graphValidationErrors.unknownEdgeSource', { nodeId }),
      unknownEdgeTarget: (nodeId: string) => t('templates.graphValidationErrors.unknownEdgeTarget', { nodeId }),
      advanceNotForward: (from: string, to: string) => t('templates.graphValidationErrors.advanceNotForward', { from, to }),
      rejectNotBackward: (from: string, to: string) => t('templates.graphValidationErrors.rejectNotBackward', { from, to }),
      multipleAdvanceOutgoing: (nodeId: string) => t('templates.graphValidationErrors.multipleAdvanceOutgoing', { nodeId }),
      multipleAdvanceIncoming: (nodeId: string) => t('templates.graphValidationErrors.multipleAdvanceIncoming', { nodeId }),
      multipleRejectOutgoing: (nodeId: string) => t('templates.graphValidationErrors.multipleRejectOutgoing', { nodeId }),
    },
    emptyTitle: t('templates.emptyTitle'),
    removeSuggestedAgentAria: (agentId: string) => t('templates.removeSuggestedAgentAria', { agentId }),
    stageNameAria: (stageId: string) => t('templates.stageNameAria', { stageId }),
    stageDeleteAria: (stageId: string) => t('templates.stageDeleteAria', { stageId }),
    stageMoveUpAria: (stageId: string) => t('templates.stageMoveUpAria', { stageId }),
    stageMoveDownAria: (stageId: string) => t('templates.stageMoveDownAria', { stageId }),
    removeRoleAria: (role: string) => t('templates.removeRoleAria', { role }),
  };
}

export function useExternalBridgesPageCopy() {
  const { t } = useTranslation();

  return {
    kicker: t('externalBridges.kicker'),
    title: t('externalBridges.title'),
    summary: t('externalBridges.summary'),
    loading: t('externalBridges.loading'),
    refreshAction: t('externalBridges.refreshAction'),
    sendAction: t('externalBridges.sendAction'),
    sending: t('externalBridges.sending'),
    createSessionAction: t('externalBridges.createSessionAction'),
    creatingSession: t('externalBridges.creatingSession'),
    switchSessionAction: t('externalBridges.switchSessionAction'),
    switchingSession: t('externalBridges.switchingSession'),
    deleteSessionAction: t('externalBridges.deleteSessionAction'),
    deletingSession: t('externalBridges.deletingSession'),
    activateProviderAction: t('externalBridges.activateProviderAction'),
    updateModelAction: t('externalBridges.updateModelAction'),
    updatingModel: t('externalBridges.updatingModel'),
    runHeartbeatAction: t('externalBridges.runHeartbeatAction'),
    runningHeartbeat: t('externalBridges.runningHeartbeat'),
    pauseHeartbeatAction: t('externalBridges.pauseHeartbeatAction'),
    pausingHeartbeat: t('externalBridges.pausingHeartbeat'),
    resumeHeartbeatAction: t('externalBridges.resumeHeartbeatAction'),
    resumingHeartbeat: t('externalBridges.resumingHeartbeat'),
    updateHeartbeatAction: t('externalBridges.updateHeartbeatAction'),
    updatingHeartbeat: t('externalBridges.updatingHeartbeat'),
    sendPlaceholder: t('externalBridges.sendPlaceholder'),
    newSessionPlaceholder: t('externalBridges.newSessionPlaceholder'),
    emptyValue: t('externalBridges.emptyValue'),
    emptyProjects: t('externalBridges.emptyProjects'),
    emptySessions: t('externalBridges.emptySessions'),
    emptyDetail: t('externalBridges.emptyDetail'),
    emptyHistory: t('externalBridges.emptyHistory'),
    emptyProjectSelection: t('externalBridges.emptyProjectSelection'),
    metrics: {
      binary: t('externalBridges.metrics.binary'),
      management: t('externalBridges.metrics.management'),
      projects: t('externalBridges.metrics.projects'),
      sessions: t('externalBridges.metrics.sessions'),
    },
    panels: {
      inspectionKicker: t('externalBridges.panels.inspectionKicker'),
      inspectionTitle: t('externalBridges.panels.inspectionTitle'),
      projectsKicker: t('externalBridges.panels.projectsKicker'),
      projectsTitle: t('externalBridges.panels.projectsTitle'),
      sessionsKicker: t('externalBridges.panels.sessionsKicker'),
      sessionsTitle: t('externalBridges.panels.sessionsTitle'),
      detailKicker: t('externalBridges.panels.detailKicker'),
      detailTitle: t('externalBridges.panels.detailTitle'),
    },
    cards: {
      binary: {
        kicker: t('externalBridges.cards.binary.kicker'),
        foundLabel: t('externalBridges.cards.binary.foundLabel'),
      },
      management: {
        kicker: t('externalBridges.cards.management.kicker'),
        reachableLabel: t('externalBridges.cards.management.reachableLabel'),
        versionLabel: t('externalBridges.cards.management.versionLabel'),
      },
      config: {
        kicker: t('externalBridges.cards.config.kicker'),
        portLabel: t('externalBridges.cards.config.portLabel'),
        existsLabel: t('externalBridges.cards.config.existsLabel'),
        tokenLabel: t('externalBridges.cards.config.tokenLabel'),
      },
    },
    labels: {
      available: t('externalBridges.labels.available'),
      unavailable: t('externalBridges.labels.unavailable'),
      online: t('externalBridges.labels.online'),
      offline: t('externalBridges.labels.offline'),
      active: t('externalBridges.labels.active'),
      live: t('externalBridges.labels.live'),
      heartbeatOn: t('externalBridges.labels.heartbeatOn'),
      heartbeatOff: t('externalBridges.labels.heartbeatOff'),
      managementStatus: t('externalBridges.labels.managementStatus'),
      projectConfig: t('externalBridges.labels.projectConfig'),
      bridgeAdapters: t('externalBridges.labels.bridgeAdapters'),
      sessionDetail: t('externalBridges.labels.sessionDetail'),
      sessionKey: t('externalBridges.labels.sessionKey'),
      agentSessionId: t('externalBridges.labels.agentSessionId'),
      sendMessage: t('externalBridges.labels.sendMessage'),
      newSession: t('externalBridges.labels.newSession'),
      sessionActions: t('externalBridges.labels.sessionActions'),
      providers: t('externalBridges.labels.providers'),
      models: t('externalBridges.labels.models'),
      setModel: t('externalBridges.labels.setModel'),
      heartbeatStatus: t('externalBridges.labels.heartbeatStatus'),
      heartbeatRunning: t('externalBridges.labels.heartbeatRunning'),
      heartbeatPaused: t('externalBridges.labels.heartbeatPaused'),
      heartbeatInterval: t('externalBridges.labels.heartbeatInterval'),
      platforms: t('externalBridges.labels.platforms'),
      sessions: t('externalBridges.labels.sessions'),
      heartbeat: t('externalBridges.labels.heartbeat'),
      agentMode: t('externalBridges.labels.agentMode'),
      mode: t('externalBridges.labels.mode'),
      history: t('externalBridges.labels.history'),
      lastRun: t('externalBridges.labels.lastRun'),
    },
    feedback: {
      sendSuccessTitle: t('externalBridges.feedback.sendSuccessTitle'),
      sendSuccessDetail: t('externalBridges.feedback.sendSuccessDetail'),
      sessionCreateSuccessTitle: t('externalBridges.feedback.sessionCreateSuccessTitle'),
      sessionCreateSuccessDetail: t('externalBridges.feedback.sessionCreateSuccessDetail'),
      modelUpdateSuccessTitle: t('externalBridges.feedback.modelUpdateSuccessTitle'),
      modelUpdateSuccessDetail: t('externalBridges.feedback.modelUpdateSuccessDetail'),
      heartbeatUpdateSuccessTitle: t('externalBridges.feedback.heartbeatUpdateSuccessTitle'),
      heartbeatUpdateSuccessDetail: t('externalBridges.feedback.heartbeatUpdateSuccessDetail'),
    },
  };
}

export function useSettingsPageCopy() {
  const { t } = useTranslation();

  return {
    sectionLabel: t('shell.nav.settings.label'),
    kicker: t('settings.kicker'),
    title: t('settings.title'),
    summary: t('settings.summary'),
    gatewayKicker: t('settings.gatewayKicker'),
    gatewayTitle: t('settings.gatewayTitle'),
    endpointLabel: t('settings.endpointLabel'),
    tokenLabel: t('settings.tokenLabel'),
    tokenPlaceholder: t('settings.tokenPlaceholder'),
    tokenHideLabel: t('settings.tokenHideLabel'),
    tokenShowLabel: t('settings.tokenShowLabel'),
    refreshKicker: t('settings.refreshKicker'),
    refreshTitle: t('settings.refreshTitle'),
    refreshLabel: t('settings.refreshLabel'),
    pauseLabel: t('settings.pauseLabel'),
    appearanceKicker: t('settings.appearanceKicker'),
    appearanceTitle: t('settings.appearanceTitle'),
    appearanceDescriptions: {
      light: t('settings.appearanceDescriptions.light'),
      dark: t('settings.appearanceDescriptions.dark'),
      system: t('settings.appearanceDescriptions.system'),
    },
    appearanceLabels: {
      light: t('settings.appearanceLabels.light'),
      dark: t('settings.appearanceLabels.dark'),
      system: t('settings.appearanceLabels.system'),
    },
    languageKicker: t('settings.languageKicker'),
    languageTitle: t('settings.languageTitle'),
    saveAction: t('settings.saveAction'),
    testAction: t('settings.testAction'),
    cleanupAction: t('settings.cleanupAction'),
    cleanupSuccess: (count: number) => t('settings.cleanupSuccess', { count }),
    healthSuccess: t('settings.healthSuccess'),
    healthFailureFallback: t('settings.healthFailureFallback'),
    healthLoading: t('settings.healthLoading'),
    accessKicker: t('settings.accessKicker'),
    accessTitle: t('settings.accessTitle'),
    accessSummary: t('settings.accessSummary'),
    accountKicker: t('settings.accountKicker'),
    accountTitle: t('settings.accountTitle'),
    accountSummary: t('settings.accountSummary'),
    sessionLabels: {
      actor: t('settings.sessionLabels.actor'),
      role: t('settings.sessionLabels.role'),
      method: t('settings.sessionLabels.method'),
    },
    roleLabels: {
      admin: t('settings.roleLabels.admin'),
      member: t('settings.roleLabels.member'),
    },
    adminOnlyNotice: t('settings.adminOnlyNotice'),
    reloadAccountsAction: t('settings.reloadAccountsAction'),
    loadingAccounts: t('settings.loadingAccounts'),
    noAccounts: t('settings.noAccounts'),
    createUserTitle: t('settings.createUserTitle'),
    usernameLabel: t('settings.usernameLabel'),
    passwordLabel: t('settings.passwordLabel'),
    createUserAction: t('settings.createUserAction'),
    resetPasswordAction: t('settings.resetPasswordAction'),
    disableUserAction: t('settings.disableUserAction'),
    bindIdentityTitle: t('settings.bindIdentityTitle'),
    providerLabel: t('settings.providerLabel'),
    externalUserIdLabel: t('settings.externalUserIdLabel'),
    bindIdentityAction: t('settings.bindIdentityAction'),
    userIdentityEmpty: t('settings.userIdentityEmpty'),
    enabledLabel: t('settings.enabledLabel'),
    disabledLabel: t('settings.disabledLabel'),
    operationMessages: {
      loadFailedTitle: t('settings.operationMessages.loadFailedTitle'),
      createSuccessTitle: t('settings.operationMessages.createSuccessTitle'),
      createSuccessDetail: (username: string) => t('settings.operationMessages.createSuccessDetail', { username }),
      createFailedTitle: t('settings.operationMessages.createFailedTitle'),
      passwordSuccessTitle: t('settings.operationMessages.passwordSuccessTitle'),
      passwordSuccessDetail: (username: string) => t('settings.operationMessages.passwordSuccessDetail', { username }),
      passwordFailedTitle: t('settings.operationMessages.passwordFailedTitle'),
      disableSuccessTitle: t('settings.operationMessages.disableSuccessTitle'),
      disableSuccessDetail: (username: string) => t('settings.operationMessages.disableSuccessDetail', { username }),
      disableFailedTitle: t('settings.operationMessages.disableFailedTitle'),
      identitySuccessTitle: t('settings.operationMessages.identitySuccessTitle'),
      identitySuccessDetail: (username: string) => t('settings.operationMessages.identitySuccessDetail', { username }),
      identityFailedTitle: t('settings.operationMessages.identityFailedTitle'),
    },
  };
}
